### ISSUE TITLE
consider using `vector_of<...>::type` instead of `native<...>` in unit tests

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#1]

**Comment by ccharly** [comment]
`vector_of` should be the default in any cases. Using `native` prevents emulated vector.

For example, in SSE1, there is no `native<int, tag::sse_>`. Using `vector_of` will simulate it:

```
# for SSE1
vector_of<int, 4> -> native<int, tag::emulation_<16>>
native<int, tag::sse_> -> # compilation error
```

**Comment by jfalcou** [comment]
pack<T,N> will now be the norm for testing. So this issue is moot.
