### ISSUE TITLE
Support for maskable operations

### ISSUE THREAD

**Issue by jfalcou** [agenium-scale/boost.simd#100]
To prepare the new trend of maskable operation in SIMD ISA, I am proposing to extend the mask() modifier from pointer to arbitrary values.
- f(p) will call f on p.
- f( mask(p,cond,def) ) will call or emulate a maskable f

I also ponder proposing p[cond] as a short-cut for mask(p,cond,p) so : 

```
asb( p[cond] )  
```

means computes abs(p) where cond is true and let it alone if not.

Though ?

**Comment by jfalcou** [comment]
After some discussion : 

 - masking pack will be done via `p( cond )` to prevent bugs with [] and non-pack conditions
 - When assigning a masked pack to a pack, values not selected will be replaced by default value
 - Most efficiently writable operations on masked pack will be optimized

So : 

    pack<int> x(1,2,3,4);
    pack<float> v(1,0.1,0.01,0.001);
    v( x > 2 )++; 

Will resolve to `v = if_inc(x>2, x);`

**Comment by ccharly** [comment]
You mean `v = if_inc(x > 2, v);`, not `x` right?
