### ISSUE TITLE
Guided fallback documentation

### ISSUE THREAD

**Issue by ThomasRetornaz** [agenium-scale/boost.simd#112]
Hi

(first:  sorry for add my question as issue but i don't find suitable devel/user mailing list on boost simd only (i found boost::simd subject in boost mailing list))

I currently code an image library which use tensor like container
and i want to use boost::simd facilities whenever is possible :)
Eg 
- Use it when a "view" on tensor  leads to aligned datas (no stride at all or no stride in the least significant dimensions)
- BUT fallback  to no simd "operator" when i use a "stridedview"

In https://github.com/jfalcou/boost-con-2011/blob/master/simd/simd.pdf
You exposed default fallback where no suitable architecture is found
I want to "manually" fallback regarding stride presence/absence, but i don't know how

Thanks for your help
Regards 
TR

**Comment by mgaunard** [comment]
You can query for a pack's storage status, which can be "emulated", "native" or "aggregated".
Is that what you want?

**Comment by jfalcou** [comment]
You basically want to force "emulation" on pack whenever some condition is true instead of using the proposed default cardinal, right ? The end effects being to be able to use a single Boost.SIMD code for both.

I think you can just change the way you load the data on your side (using load ith either a scalar or a SIMD output type) and use the boost.SIMD functions on w/e gets in.

```
using is_strided = some_static_choice_on_using_stride< my_view_type>::type;
using target_type = std::conditional< is_strided::value, my_view_type::value_type, pack<my_view_type::value_type>>;

// it's pack is no strode, a scalar otherwise
auto x = load<target_type>( my_view.data(), my_offset );

// will do the correct thing
x = boot::simd::cos(x)  + x;
```

Basically, check if you want scalar or pack types, then load the data as you want and use the functions generically.

**Comment by ThomasRetornaz** [comment]
@mgaunard thanks for your quick answers

@jfalcou Yep force emulation seems to do the job

I will try our proposal on force "emulation"

Thanks you both
Regards
TR

**Comment by jfalcou** [comment]
FYI, The emulation status is accessible via the pack  ::storage_kind internal type definition.

**Comment by jfalcou** [comment]
is this closable or do you have any other issue ?

**Comment by ThomasRetornaz** [comment]
Yes its closable
I have plenty of questions/issue :)
Is there exist something like forum/faq for boost::simd and nt2?
Regards TR

**Comment by jfalcou** [comment]
We're pulling a proper one for boost.SIMD, yes.
For NT2 question, you can mail on nt2-dev@google-groups.com
