### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by alankelly** [agenium-scale/boost.simd#122]
There is a huge amount of aliases in boost.simd. Is this really necessary? I fail to see how this enhances the library. In my opinion, it adds clutter to the library and makes it more difficult to maintain and use.

I recommend deprecating all alias functions and removing them in a future release.

Opinions please!

Examples include modulo = mod, remainder = rem, drem = rem...etc

**Comment by jfalcou** [comment]
See what we spoke about in https://github.com/NumScale/boost.simd/issues/22
Some alias are here to have a proper std like name. We can arge that only the std name is useful.

Note that we removed a crap ton of them already.

**Comment by jtlap** [comment]
I don't want to deprecate all aliases

Some boost.simd functions have names that make sense but there is a stdlibc++ fonction
that has the same behaviour with another name and I thhink that an alias for that is good.

All boolean functors still must have their names unified and modified, this will remove many aliases
but I thik that pairs as if_allbits_else and if_nan_else must be kept for clarity

the remainder class can also be treated as the div(ides) one

**Comment by jfalcou** [comment]
It came to my realization that some aliases I thought were goen are not. All oeprators liek == etc still have fortran liek function like equivalent. These need to go and so does their unit tests

**Comment by jfalcou** [comment]
Pull Request #133 is removing a lot except for shl,ifix,fix,bitwise_not
- shl stays to be simetric with shr
- ifix/fix is a shortcut to saturated_(toint).
- bitwise_not is there to be symmetric ith other bitwise_*. It is complement but maybe complement is the one to remove.

**Comment by alankelly** [comment]
This looks good to me. Thanks!
