### ISSUE TITLE
Reduce unnecessary temporaries, enforce const strictness

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#13]
[original issue here](https://github.com/jfalcou/nt2/issues/46).

**Comment by psiha** [comment]
...was this one also closed by mistake? :)

**Comment by jfalcou** [comment]
Nope, this was my intended target. We moved this to our internal wiki of what to do.
We're gonna fix and updates code as we go by. This is not an issue per se as I the condition for closign is open-ended.

**Comment by jfalcou** [comment]
We also have to make the 'codegen' target active after fixing our CMake handlign it so we cna check the codegen directly from the make targets and guide us into optimizing code properly.
