### ISSUE TITLE
Doc functions to review

### ISSUE THREAD

**Issue by alankelly** [agenium-scale/boost.simd#131]
ifix

**Comment by alankelly** [comment]
Find a valid use case for a large pack and make an example.

**Comment by jfalcou** [comment]
pack<double,4> used as 3D vector + normalization is an exampel I found around. Yes, it should not be used like this but it lookslike a valid case where fixed size as a parameter is used. IIRC ISPC has an example dealing with ray tracing around this. It's probably a bit complicated and shoudl be handled by pack<double[4]> later instead.

This has to be a advanced topic in the tutorial anyway
