### ISSUE TITLE
Error compiling the README example

### ISSUE THREAD

**Issue by superbobry** [agenium-scale/boost.simd#134]
Hi, I've followed the steps outlined in the README: successfully compiled Boost.SIMD, installed it into a temporary directory and attempted to compile `main.cpp`. 

Unfortunately, compilation failed with

```
/tmp/main.cpp:9:16:   required from here
/tmp/boost.simd.install/include/boost/simd/arch/x86/sse1/simd/function/splat.hpp:34:25: error: invalid static_cast from type ‘const float [4]’ to type ‘float’
       return _mm_set1_ps( static_cast<float>(v) );
```

Configuration: Ubuntu 15.10, Boost 1.60 and

```
$ g++ --version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jfalcou** [comment]
Seems the passing of array is a bit rough. Can you try changing  

```
pack_t p{data};
```

by

```
pack_t p{&data[0]};
```

I'll amend pack constructor to handle this a bit better.

**Comment by jfalcou** [comment]
FYI, I also added aconstructor for pack taking a std::array as input.

**Comment by superbobry** [comment]
Thanks, I was able to successfully compile & run the example.

**Comment by jfalcou** [comment]
@superbobry Great. Keep us in touch if you need any help.
