### ISSUE TITLE
boost::simd minus

### ISSUE THREAD

**Issue by alankelly** [agenium-scale/boost.simd#139]
The following code generates a huge amount of unnecessary instructions. Compiled with g++-4.9 with sse4.2. Plus generates correct instructions.

bs::pack<int> full_out, full_arr, full_128;
full_out = full_arr - full_128;  

 400a4b:       4c 8d 6c 24 30          lea    0x30(%rsp),%r13
  400a50:       48 8d bc 24 c0 00 00    lea    0xc0(%rsp),%rdi
  400a57:       00 
  400a58:       4c 89 a4 24 c0 00 00    mov    %r12,0xc0(%rsp)
  400a5f:       00 
  400a60:       48 c7 84 24 c8 00 00    movq   $0x0,0xc8(%rsp)
  400a67:       00 00 00 00 00 
  400a6c:       4c 89 ac 24 b0 00 00    mov    %r13,0xb0(%rsp)
  400a73:       00 
  400a74:       48 c7 84 24 b8 00 00    movq   $0x0,0xb8(%rsp)
  400a7b:       00 00 00 00 00 
  400a80:       e8 7b 02 00 00          callq  400d00 <boost::simd::detail::pack_proxy<boost::simd::pack<int, 4ul, boost::simd::sse_> const>::operator int() const>
  400a85:       48 8d bc 24 b0 00 00    lea    0xb0(%rsp),%rdi
  400a8c:       00 
  400a8d:       41 89 c6                mov    %eax,%r14d
  400a90:       e8 6b 02 00 00          callq  400d00 <boost::simd::detail::pack_proxy<boost::simd::pack<int, 4ul, boost::simd::sse_> const>::operator int() const>
  400a95:       48 8d bc 24 a0 00 00    lea    0xa0(%rsp),%rdi
  400a9c:       00 
  400a9d:       44 29 f0                sub    %r14d,%eax
  400aa0:       4c 89 a4 24 a0 00 00    mov    %r12,0xa0(%rsp)
  400aa7:       00 
  400aa8:       89 44 24 08             mov    %eax,0x8(%rsp)
  400aac:       48 c7 84 24 a8 00 00    movq   $0x1,0xa8(%rsp)
  400ab3:       00 01 00 00 00 
  400ab8:       4c 89 ac 24 90 00 00    mov    %r13,0x90(%rsp)
  400abf:       00 
  400ac0:       48 c7 84 24 98 00 00    movq   $0x1,0x98(%rsp)
  400ac7:       00 01 00 00 00 
  400acc:       e8 2f 02 00 00          callq  400d00 <boost::simd::detail::pack_proxy<boost::simd::pack<int, 4ul, boost::simd::sse_> const>::operator int() const>
  400ad1:       48 8d bc 24 90 00 00    lea    0x90(%rsp),%rdi
  400ad8:       00 
  400ad9:       41 89 c7                mov    %eax,%r15d
  400adc:       e8 1f 02 00 00          callq  400d00 <boost::simd::detail::pack_proxy<boost::simd::pack<int, 4ul, boost::simd::sse_> const>::operator int() const>
  400ae1:       48 8d bc 24 80 00 00    lea    0x80(%rsp),%rdi
  400ae8:       00 
  400ae9:       44 29 f8                sub    %r15d,%eax
  400aec:       4c 89 a4 24 80 00 00    mov    %r12,0x80(%rsp)
  400af3:       00 
  400af4:       41 89 c6                mov    %eax,%r14d
  400af7:       48 c7 84 24 88 00 00    movq   $0x2,0x88(%rsp)
  400afe:       00 02 00 00 00 
  400b03:       4c 89 6c 24 70          mov    %r13,0x70(%rsp)
  400b08:       48 c7 44 24 78 02 00    movq   $0x2,0x78(%rsp)
  400b0f:       00 00 
  400b11:       e8 ea 01 00 00          callq  400d00 <boost::simd::detail::pack_proxy<boost::simd::pack<int, 4ul, boost::simd::sse_> const>::operator int() const>
  400b16:       48 8d 7c 24 70          lea    0x70(%rsp),%rdi
  400b1b:       41 89 c7                mov    %eax,%r15d
  400b1e:       e8 dd 01 00 00          callq  400d00 <boost::simd::detail::pack_proxy<boost::simd::pack<int, 4ul, boost::simd::sse_> const>::operator int() const>
  400b23:       48 8d 7c 24 60          lea    0x60(%rsp),%rdi
  400b28:       44 29 f8                sub    %r15d,%eax
  400b2b:       4c 89 64 24 60          mov    %r12,0x60(%rsp)
  400b30:       89 44 24 0c             mov    %eax,0xc(%rsp)
  400b34:       48 c7 44 24 68 03 00    movq   $0x3,0x68(%rsp)
  400b3b:       00 00 
  400b3d:       4c 89 6c 24 50          mov    %r13,0x50(%rsp)
  400b42:       48 c7 44 24 58 03 00    movq   $0x3,0x58(%rsp)
  400b49:       00 00 
  400b4b:       e8 b0 01 00 00          callq  400d00 <boost::simd::detail::pack_proxy<boost::simd::pack<int, 4ul, boost::simd::sse_> const>::operator int() const>
  400b50:       48 8d 7c 24 50          lea    0x50(%rsp),%rdi
  400b55:       41 89 c4                mov    %eax,%r12d
  400b58:       e8 a3 01 00 00          callq  400d00 <boost::simd::detail::pack_proxy<boost::simd::pack<int, 4ul, boost::simd::sse_> const>::operator int() const>

**Comment by jtlap** [comment]
This pull request fixes the issue
