### ISSUE TITLE
Aggregate used for larger pack

### ISSUE THREAD

**Issue by alankelly** [agenium-scale/boost.simd#141]
The automatic generation of a tuple of pack when the size given to a pack is larger than a native SIMD register size may be quite dangerous for inexperienced users. The similarities between this and an std::array combined with the fact that this facilitates the writing of inefficient code makes me think that this option should be blocked by default and only enabled through the definition of a macro. For example, if one wishes to subtract a constant from a large pack, the following code may seem sensible:

(SIZE is larger than cardinal of native SIMD vector)
`pack<int, SIZE> a //fill a with data`
`pack<int, SIZE> sub = constant_data; //data to subtract`
`pack<int, SIZE> res = a - sub;`

In this case here, the code generated is very inefficient and it cannot be caught by the boost.simd during the code generation process. Any user testing boost.simd with such a trivial example could easily believe that boost.SIMD generates very poor code and is not a high performance library. Also, the ability to simdize code requires thinking at the register level and having some understanding of how registers and simd instructions work. The use of a higher level abstraction than the native register does not encourage such thinking so may lead to poor code, also very few algorithms are amenable for use with such an abstraction. For these reasons I propose that `pack<T, N>` be deactivated by default.

**Comment by alankelly** [comment]
****For these reasons I propose that boost::simd::pack<T, N> be deactivated by default. 
:smile:

**Comment by jtlap** [comment]
perhaps you are right, bit in this case we must have something as  halfpack<T> and doublepakk<T>
(with the obvious meaning) that can be not so bad and aleviate many corner cases, if the other values of N are to be disabled.

**Comment by jfalcou** [comment]
the code is inneficient because std::array dont have forceinlined ctor (as it does not have any).
The correct fix is probably to use T[N] internally and warn people that largish is frowned upon by adding a static_assert with a sensible max cardinal.

Also rememebr we use combine a lot internally and there's no sane way to change this behavior.
I'm not changing the API and internals because people don't read documentation.

**Comment by jfalcou** [comment]
Also, IIRC, we already check for non-power of 2 cardinals so normally people can't even use pack as array becasue `pack<T,17>` will refuse to compile.

The more I think of it, the more a large warning in the doc and entry point example not speakign of the N parameter is probably enough (in addition to fixing the last codegen issue).

**Comment by alankelly** [comment]
I strongly disagree on this point. Nobody reads the doc, people download, compile and if it doesn't work first time, or if the performance is not good, they blame the library, never themselves. Only serious, committed users read the doc, not those who are just quickly trying out the library. We want to catch as many of these users as possible, otherwise, we will lose sales and users. 

It is our job to make the interface as easy as possible to use and to make it as difficult as possible to write poor code. The best ways to do this are an interface which prevents this kind of behaviour and a quick start guide which covers as much as reasonably possible while still short enough that someone might actually read it.

If it is possible to do something silly, people will do it. We are aiming to have as many users as possible on the open-source version and to transform as many of these onto the premium version.

**Comment by jfalcou** [comment]
My point is that it's mainly a matter of fixing the wrong codegen due to std::array. When the better_stores branch lands, I guess the codegen will be far better.

As for trying out the library, if the first example show pack and not pack with custom N, I don't see the issue. Just make custom sized pack a late point in the doc.

**Comment by jfalcou** [comment]
Maybe we can take a page from  

http://stackoverflow.com/questions/8936063/does-there-exist-a-static-warning

and add such static_warning to the pack definition hence making the Size>natural cardinal case noisy.

**Comment by alankelly** [comment]
I'm not too convinced on the static warning presented there, it's quite hacky, not a solution to be shipped in software of the quality of boost.simd. 

I'm wondering why you're so keen on keeping functionality which you struggle to find valid use cases for?

I like jtlap's solution with halfpack, doublepack. The code I presented will always be inefficient regardless on what magic you manage to do behind the scenes creating a clone of std::array with inlined ctor.

There's also my other point, in that using packs of sizes which don't correspond with a native vector size fundamentally encourages the writing of inefficient code. I believe that this will increase the time we spend supporting clients.

**Comment by ccharly** [comment]
As the library is not in its final state we can still fix those codegen issues and try to see if there is any other way we can prevent people from doing this. Having some nice types such as `{double,half}_pack` could be an idea, at least, for internal usage. 

I strongly agree on the fact that some people will try big packs and end up with _probably_ crappy performance. We could use some sort of `extended_pack` types maybe, and write documentation about it in "Advanced Section" or whatever we're gonna call it.

IMHO, some people will ask for this feature while some people that are already used to current SIMD philosophy will use pack as is.

**Comment by jfalcou** [comment]
Also remember we need extra-sized pack for handlng integer on AVX as the old way of doign it was generating huge amount of insert/extract.

**Comment by mgaunard** [comment]
The ability to specify an arbitrary power-of-two N is pretty important as far as I'm concerned. A lot of code just cannot be written portably without that feature.
double/half pack is not sufficient as there are no guarantee that the register width is the same for all types.
I'm also fighting at the C++ standard to get proper support for this.

If it's an implementation problem, it can just be fixed.

**Comment by jfalcou** [comment]
As one of our concern is finding a decent example of those large pack usage, any pointer to such usage could be great. I guess sorting is one but it's hardly a simple example.

**Comment by jfalcou** [comment]
Also, I know @timblechmann also uses this generic sizing facility, maybe he can shed a light on those.

**Comment by timblechmann** [comment]
i have some use cases, which are really suited for `pack<float, 8>` (iirc some 8-point interpolations). also, i have some use cases for pack<float, N>, though this could probably also be handled via one-dimensional `nt2::table`s.

**Comment by jfalcou** [comment]
OK, care to share one of those 8-pack use case or something similar but not critical ?

@alankelly I think one way to improve generated code is to use a simple pair instead of array. I'll give it a try.

**Comment by mgaunard** [comment]
If you have weaker guarantees than what Boost.SIMD currently provides, you could have a `pack<float>`  of size 8 and a `pack<int>` of size 4.
If you need to converts floats to ints, you'd then have to write something like:

```
pack<float> a;
pack<int, a.size()> b = cast<int>(a); /* assuming there was a 'cast' function,
                                         the standard is considering making it implicit instead */
```

It's even worse if you want to convert between double and int, we don't even have a proper way of doing that in Boost.SIMD at the moment, mainly because we're stuck in the "a variable is a register" model.

Other examples include working with images, you need to promote from int8 to int16 (or float), end up with twice (or four times) as many data where you need to repeat your operations. Working with a single pack 2/4 times as large would fix it too.

**Comment by jfalcou** [comment]
This is in our todo list, yes. As we changed the basic implementation to be pack<T,N> instead of the old native, we're aware of opportunity like those. This is probably being done for the next milestone after completing the transition.

**Comment by jfalcou** [comment]
Discussing this a bit,maybe having a static_assert that checks that total size of the pack don't overflow a cache line is an idea. Said assert can be deactivated by a macro when ppl know what they do.

**Comment by mgaunard** [comment]
A SIMD register _is_ a cache line on some architectures, so that means you couldn't double the native size for example.

**Comment by jfalcou** [comment]
OK, basically, we're down to introduce the larger pack is a thing as late as possible in the quick start guide.
