### ISSUE TITLE
Very slow nt2::abs on complex

### ISSUE THREAD

**Issue by serge-sans-paille** [agenium-scale/boost.simd#147]
(moving from https://github.com/serge-sans-paille/pythran/issues/433)

The following c++ code:

``` c++
#include <complex>
#include <nt2/sdk/complex/complex.hpp>
#include <nt2/include/functions/abs.hpp>

int main(int argc, char**argv) {
  std::complex<double> c0;
  std::complex<double> c1 = nt2::abs(c0);
  return c1.real() ==0;
}   
```

when compiled using a (frozen) version of nt2 / boost.simd, is twice as slow as std::abs... A quick look at the generated assembly points out an unexpected

```
    movsd   %xmm2, (%rsp)
    call    ilogb
```

ilogb? what for?

**Comment by jfalcou** [comment]
Let's see what @jtlap has to say on this.
Which HEAD of the old NT2 are you using ?

**Comment by serge-sans-paille** [comment]
https://github.com/pbrunet/nt2/tree/gemv_release

**Comment by mgaunard** [comment]
That's because nt2's complex abs is hypot (which avoids overflow and is properly rounded), while libstdc++ uses a naive implementation.
The same is true for all complex operations at present, which cause them to be extremely slow.

**Comment by serge-sans-paille** [comment]
On Wed, Jun 01, 2016 at 01:18:23AM -0700, Mathias Gaunard wrote:

> That's because nt2's complex abs is hypot (which avoids overflow and is properly rounded), while libstdc++ uses a naive implementation.
> The same is true for all complex operations at present, which cause them to be extremely slow.

Any macro I could use to have a more naive behavior?

**Comment by mgaunard** [comment]
Not really no.
It needs an overhaul, I think it should mimic typical C++ behaviour and that the higher accuracy variants should be special functions.

But anyway this is nt2, not boost.simd; doesn't look like the right bug tracker.

**Comment by jfalcou** [comment]
Closed here and referenced on NT2 issue tracker

**Comment by jtlap** [comment]
We plan to integrate complex number support in boost.simd, and them there will be "fast" versions
of many functions and perhaps a "fast" mode (ifdefed). NT2 however will not change for long its complex behaviour.

**Comment by mgaunard** [comment]
is the goal to move all simd functions from nt2 to boost.simd then?

**Comment by jtlap** [comment]
no, nearly the standard supported scalar functions in order to have simd equivalent behaviour to standard calls.
