### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by jfalcou** [agenium-scale/boost.simd#149]
- remove reference to boost dispatch as it's now all inclusive
- fix the code example which is wrong (pack(T*) require aligned memory)

**Comment by jfalcou** [comment]
maybe take a page from the upcoming new doc @alankelly ?

**Comment by ccharly** [comment]
I don't even know if you need that "kind of" documentation in the README? Just include a link to the actual doc should be enough?

**Comment by jfalcou** [comment]
We need :a small blurb of presentation,  links to the doc, a small gotcha sample code and otehr infos like ML and IRC channels

**Comment by ccharly** [comment]
I've updated the current README.md with a totally different example that uses aligned memory now. See [here](https://github.com/NumScale/boost.simd/commit/ee01d5f1c68c96505449bd648d35d6010bfdcbce). This is probably enough for now?

**Comment by superbobry** [comment]
A link to an IRC channel would be quite helpful for quick questions.

**Comment by jfalcou** [comment]
Made another roudn with a0ed2aba8211c54f9fc42693371b42ae543acdd0
We need to setup the IRC channel and add it later
