### ISSUE TITLE
No rule to make target `update.boost.dispatch'

### ISSUE THREAD

**Issue by superbobry** [agenium-scale/boost.simd#162]
Are instructions in the README out of date? 

The Makefile produced by `cmake` is missing the aforementioned target.

**Comment by ccharly** [comment]
yes you're right this is outdated. `boost.dispatch` is now part of `boost.simd` directly, so no need to get it remotely. Just omit the `make update.boost.dispatch` command for now and you should be fine. Thanks for spotting that! :)

**Comment by superbobry** [comment]
Cool, thanks!
