### ISSUE TITLE
Many constants could be put in details

### ISSUE THREAD

**Issue by jtlap** [agenium-scale/boost.simd#166]
Many multitype constants could be put in detail and do not deserve documentation.
Even some could be simply defined where they are used with Constant.

Less files and less useless docs... Don't you think ?

**Comment by jfalcou** [comment]
Yes put them in detail.

**Comment by jfalcou** [comment]
Also do we still need Two, Three, Four etc now that pack splat constructor is fully functionnal ? Zero is a bit special as it can use a special intrinsics, but the others ?
