### ISSUE TITLE
Dispatch on instruction set

### ISSUE THREAD

**Issue by superbobry** [agenium-scale/boost.simd#167]
nt2 has a way of provided instruction set specific implementations via `BOOST_SIMD_DEAFULT_SITE` and `boost::simd::is_supported`. Is there similar functionality in the new `boost.simd`?

**Comment by jfalcou** [comment]
we moved from this model to only have a size based pack available. What's exactly your use case ?
Also note that pack<T> already give you the correctly sized pack you may need.

**Comment by superbobry** [comment]
I'm doing vectorized speedups for Java code and I'd like to load either sse2 or avx-compiled version depending on the instruction set supported by the CPU.

**Comment by jfalcou** [comment]
OK, yes we need to reimplement that back from NT2.

**Comment by superbobry** [comment]
Just a clarification. I don't need the dispatch mechanism per se. Having runtime feature detection is good enough for my use-case. 

Right now I'm using a hand-rolled version which I'd be happy to drop in favour of `is_supported<>` :)

**Comment by jfalcou** [comment]
I was speaking of is_supported. 
For the other one, we have poeple requesting a `hw_pack<T,Ext>` alias that give you the pack of T with the proper ize of a native register on hardware Ext. This also may be useful.

**Comment by jfalcou** [comment]
Currently implemented in #234
