### ISSUE TITLE
Do not clone external projects implicitly

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#169]
The cmake should not extract all those dependencies directly as it is only useful internally. We could probably add a `-DNS_DEV` or whatever else to explicitly enable those dependencies.

The default cmake should only have one rule which would be the `install` rule.

**Comment by jfalcou** [comment]
mayeb also bench and test ?

**Comment by ccharly** [comment]
yes, I was also talking about them! :)

**Comment by ccharly** [comment]
d197b36ae773566f043161bbf99d73a723edf03e

**Comment by jfalcou** [comment]
Megred in 7b6d691
