### ISSUE TITLE
type casts for boost.simd types

### ISSUE THREAD

**Issue by timblechmann** [agenium-scale/boost.simd#17]
it would be great to be able to cast between packs (or other boost.simd types) of the same size with an API function ... e.g. from `pack<float, N>` to `pack<double, N>`

**Comment by ccharly** [comment]
hi,

yes you're right. I think we've already discussed with @jfalcou about this, this is in our todo-list! ;)

**Comment by jfalcou** [comment]
I propose : 
`cast<T>(U)`

so it's not implicit.

**Comment by otristan** [comment]
Tim example seems to be a split actually, no ?
The cardinal do not change in his example.
A cast would be
`pack<int16_t, 8> to pack<int32_t, 4>`

Am I missing something ?

**Comment by timblechmann** [comment]
there are good use cases for `pack<int16_t, 8>` to `pack<int32_t, 4>` and for `pack<int16_t, 8>` to `pack<int32_t, 8>`.

an expressive naming is another thing :)

**Comment by otristan** [comment]
well, it's just that's how it's currently named in boost simd to do that kind of operations when type are upgraded.

See
https://github.com/NumScale/boost.simd/issues/224

**Comment by jfalcou** [comment]
cast must supports all sensible {T,N} <-> {U,M} conversion. It's basically a meta-wrapper around succesion of split, specific intrinsic (like the unused `_mm_cvtpd_epi32`) and have a fallback of filling the register piecewise.

Casting using split is the current way of doing it and this + Tim's use cases just show we need a centralized entry point for this cast.

**Comment by otristan** [comment]
what would be the current/correct way of doing 

`pack<int16_t, 8> to pack<int32_t, 4>`

without avoiding recopy then ?

**Comment by jfalcou** [comment]
You want `pack<int16_t, 8>` to `pack<int32_t, 8>` as the {int32,8} will be an aggregate of the correct type. {{int32,4},2}

You can't change the cardinal while casting as you'll lose data.

**Comment by otristan** [comment]
nop, please read my comment.
I want `pack<int16_t, 8> to pack<int32_t, 4>`
equivalent of a reinterpret_cast
like I have 4 x int32_t that I want to use as 8 x int16_t and vice versa.

**Comment by jfalcou** [comment]
Shoudl have got a coffee before replying. 

The proper equivalent to reintepret_cast (ie you have two types of same sizeof and you want to keep the bit patterns inside) is boost::simd::bitwise_cast<T>(U const& u)

**Comment by jfalcou** [comment]
FYI, this depends on #11

**Comment by jtlap** [comment]
for my point of view cast<T>(a) will be an extension of static_cast
T is always a scalar type.
If the U type of a is another one this is static_cast<T>(a)
If U i s a pack of cardinal N this is equivalent to produce a pack of same cardinality with each element static casted to type T

Moreover the narrowing cases will be don't care/undefined  for cast and saturate for saturated_(cast) that can be written in a second pass

**Comment by jtlap** [comment]
for my point of view cast<T>(a) will be an extension of static_cast
T is always a scalar type.
If the U type of a is another one this is static_cast<T>(a)
If U i s a pack of cardinal N this is equivalent to produce a pack of same cardinality with each element static casted to type T

Moreover the narrowing cases will be don't care/undefined  for cast and saturate for saturated_(cast) that can be written in a second pass
