### ISSUE TITLE
boost::simd::sum is broken

### ISSUE THREAD

**Issue by superbobry** [agenium-scale/boost.simd#171]
I've modified the example in the README as follows:

``` cpp
#include <boost/simd/function/sum.hpp>

template <typename T>
void iota_and_print()
{
  // ...
  std::cout << p << " sum(.) = " << boost::simd::sum(p) << std::endl;  
}
```

and the output is

```
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16) sum(.) = 
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16) sum(.) = 
(1, 2, 3, 4, 5, 6, 7, 8) sum(.) = 1
(1, 2, 3, 4, 5, 6, 7, 8) sum(.) = 1
(1, 2, 3, 4) sum(.) = 1
(1, 2, 3, 4) sum(.) = 1
(1, 2) sum(.) = 1
(1, 2) sum(.) = 1
(1, 2, 3, 4) sum(.) = 1
(1, 2) sum(.) = 1
```

Clearly something doesn't work right.

**Update**: I guess [this](https://github.com/NumScale/boost.simd/blob/develop/include/boost/simd/arch/common/simd/function/splatted_sum.hpp#L32) might be the reason?

**Comment by ccharly** [comment]
We know about it, the [PR](https://github.com/NumScale/boost.simd/pull/170) that is fixing it is being integrated soon. Thanks!

**Comment by superbobry** [comment]
Yeah, I wish this was documented somewhere. Spent quite a while debugging the failing tests.

Also, it seems `cumsum` [has](https://github.com/NumScale/boost.simd/blob/454154b8d8748936c8379ed327aff157e85d0a79/include/boost/simd/arch/common/scalar/function/cumsum.hpp#L29) similar issues and is not targeted by #170.

**Comment by jfalcou** [comment]
cumsum is in the next wagon of new code to be pushed ;)
As I said already, we're still in flux of porting/cleaing the old code. Until we got a neat tagged release 1.0, thigns may unexpectedly break or be incorrect (even if it's rarer and rarer now).

**Comment by superbobry** [comment]
Okay, thanks for the update. I'll close the issue then.

**Comment by jfalcou** [comment]
Feel free to ping us if ou ever ound others non trivial missing features. 
And thanks for your interest :)
