### ISSUE TITLE
round speed and behaviour

### ISSUE THREAD

**Issue by jtlap** [agenium-scale/boost.simd#186]
boost.simd implements round and round2even.

The one generally corresponding to simd intrinsics is round2even, but the natural call for an end user is round which is much slower.

Also the round(x,n) (to n decimal) uses slow rounding

I propose to change the names
- round2even -> round
- round -> round2inf   

meaning that the half  integer values are  always  such that abs(round2inf(a)) >= a 

and now round(x,n) will in fact use rounding to even mode

What do you think ? Now round if at least 2 times slower than round2even.

**Comment by jfalcou** [comment]
If precision is still correct, then yes do that. I want natural calls to be fast in general.

**Comment by mgaunard** [comment]
I don't think it is a good idea to depart from C and C++ standard naming.
The current boost simd round is the same behaviour as std::round.
round2even in the standard is actually nearbyint.

**Comment by mgaunard** [comment]
Also round2even doesn't actually round to even, it rounds to whatever the current rounding mode is, so nearbyint is definitely "better".

**Comment by jtlap** [comment]
No round2even actually does rounding to even up to now.

For instance in avx the call is 

_mm256_round_pd/s(a0, _MM_FROUND_TO_NEAREST_INT);

for which the doc says:
 _MM_FROUND_TO_NEAREST_INT 0x0 Round to nearest (even).

the rouding mode parameter in fact allows to choose between the current rouding mode (as Mathias said) or modes corresponding to trunc, ceil,floor and round to even. The round2inf mode does not exists.

**Comment by jtlap** [comment]
However Mathias is right for the fact that std:round is away from zero and roundaway could be a better term than round2inf that could lead to think that round2inf(-2.5) is -2.0.

nearbyint per se does not add any precision on the behavior.

So I'm still not so sure, adding that round is the most natural name so as Joel I think it as to be the fastest, but that it is also possible to have fast_(round) and std_(round)...

**Comment by mgaunard** [comment]
the common implementation of round2even rounds to the current rounding mode, indeed some of the other implementations do not.

**Comment by jfalcou** [comment]
i kinda like nearbyint as a name

**Comment by jfalcou** [comment]
Solved by aa27fec36e0969ef3eef436b78dad15fbcd353a1
