### ISSUE TITLE
Including simd.hpp on Windows gives an error

### ISSUE THREAD

**Issue by LegalizeAdulthood** [agenium-scale/boost.simd#189]
VS 2015 Update 3

```
1>------ Build started: Project: BoostSimdMandel, Configuration: Debug Win32 ------
1>  main.cpp
1>D:\Code\ucpp\SIMD\SIMD\boost\include\boost/simd/function/definition/slide.hpp(41): error C2955: 'boost::simd::cardinal_of': use of class template requires template argument list
1>  D:\Code\ucpp\SIMD\SIMD\boost\include\boost/simd/meta/cardinal_of.hpp(52): note: see declaration of 'boost::simd::cardinal_of'
1>D:\Code\ucpp\SIMD\SIMD\boost\include\boost/simd/function/definition/slide.hpp(44): error C2955: 'boost::simd::cardinal_of': use of class template requires template argument list
1>  D:\Code\ucpp\SIMD\SIMD\boost\include\boost/simd/meta/cardinal_of.hpp(52): note: see declaration of 'boost::simd::cardinal_of'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

`main.cpp` just includes `<boost/simd.hpp>`

**Comment by jfalcou** [comment]
are you using master or develop branch ?

**Comment by otristan** [comment]
Same issue here with both master and develop branch with boost 1.62

**Comment by jfalcou** [comment]
I can't reproduce this issue with latest Boost develop branch and using Cmake, cl.exe & Ninja. 

For reference, here are the options used via CMake.

`/nologo /TP /DWIN32 /D_WINDOWS /W4 /GR /fp:precise  /MDd /Oxt /D_SCL_SECURE_NO_WARNINGS /EHsc /FS`

I will run this through the IDE to see if anything changes.

**Comment by otristan** [comment]
Well I didn't tried with CMAKE as I only copied the simd dir and simd.hpp in my boost include dir.
and include in my own code.

So might be related to some flag.

By the way, the includes in .cpp of the examples dir are wrong.

boost 1.62 was retrieved from there
https://sourceforge.net/projects/boost/files/boost/snapshots/develop/

**Comment by jfalcou** [comment]
Thta's more related to #190, we're hammering and cleaning up all doc related elements at the moment.

**Comment by otristan** [comment]
I agree for the the examples.
Still, the build error is not related to this as including simd.hpp should work right ?

**Comment by jfalcou** [comment]
Yes sure, sorry the answer was sloppily written.

**Comment by otristan** [comment]
Thx !

**Comment by jfalcou** [comment]
OK, looks like I slept over updating my 1.62. A bunch of errors sneaked through. Will fix those and retest with actual MSVC SLN

**Comment by otristan** [comment]
Chaging the impl of slide.hpp to

```
namespace boost { namespace simd
{
  template<int N, typename T> BOOST_FORCEINLINE auto slide(T const& a0, T const& a1)
  BOOST_NOEXCEPT_DECLTYPE_BODY((detail::slider<T,N, 1ULL,(N>=0)>::call(a0,a1)));

  template<int N, typename T> BOOST_FORCEINLINE auto slide(T const& a0)
  BOOST_NOEXCEPT_DECLTYPE_BODY((detail::slider<T,N, 1ULL,(N>=0)>::call(a0)));
} }
```

fixes my issue.
Might be a bug in VS2015 regarding constexpr usage from std::integral_constant in a template

**Comment by jfalcou** [comment]
I'll add that to my fix_msvc branch

**Comment by jfalcou** [comment]
OK, I still can't reproduce this with MSVC2015u3

**Comment by otristan** [comment]
Off for 3 weeks. Will check when I come back. Thanks a lot.

**Comment by LegalizeAdulthood** [comment]
I followed the instructions in the README, so I was using latest from boost as cloned by cmake.

**Comment by LegalizeAdulthood** [comment]
OK, just reproduced it again:
VS 2015 Update 3
1. cloned `git@github.com:NumScale/boost.simd`
2. `cmake -G "Visual Studio 14 2015" .. -DUSE_SELF_BOOST= -DCMAKE_INSTALL_PREFIX=D:/dev/legalize/install`
3. Open VS solution file
4. build project `INSTALL`
5. Make new empty Console application in VS
6. Add `D:/dev/legalize/install/include` to include path in project
7. create `main.cpp` with `#include <boost/simd.hpp>` in it
8. compile project
9. get compilation error

Zip file containing my install output and VS project: http://user.xmission.com/~legalize/tmp/simd-mandel.zip

**Comment by LegalizeAdulthood** [comment]
If I change the code as suggested by @otristan then it compiles without error.

**Comment by jfalcou** [comment]
Ok, I'll take a look at your sln. The fix by @otristan is not valid as it makes slide not working right. I'll try to see if simplifying the logic around this point helps MSVC. I still don't understand how I am not able to reproduce the error.

**Comment by LegalizeAdulthood** [comment]
I have been bitten before by user property sheets changing the include directories and I didn't quite notice, so I ended up getting different headers than I thought I was getting.

**Comment by jfalcou** [comment]
OK got a repro and circled the issue. Will push a fix today.
