### ISSUE TITLE
floor return type issue

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#192]
I'm tracking a weird compiling issue using VS2015

The following code do not compile

```
using p_t = boost::simd::pack<float>;
p_t value{ 1.2f, 1.3f, 1.4f, 1.6f};
p_t index = boost::simd::floor(value);
```

while this one does

```
using p_t = boost::simd::pack<float>;
p_t value{ 1.2f, 1.3f, 1.4f, 1.6f};
auto index = boost::simd::floor(value);
```

index is said to be of type `boost::simd::pack<float, 4, boost::simd::sse_>` by the compiler

but this do not compile

```
using p_t = boost::simd::pack<float, 4, boost::simd::sse_>;
p_t value{ 1.2f, 1.3f, 1.4f, 1.6f};
p_t index = boost::simd::floor(value);
```

Am I missing something ?

Thanks !

**Comment by jfalcou** [comment]
Care to copy/paste the error message, your compilation flags and mode, along with your exact cl.exe version number ?

**Comment by jfalcou** [comment]
Same. Can't reproduce.

**Comment by jfalcou** [comment]
can you try the msvc_fixes branch and tell me how it goes ?
Also do you compile in x86 or x64 mode ?

**Comment by otristan** [comment]
Off for 3 weeks. Will check when I come back. Thanks a lot.

**Comment by otristan** [comment]
Works fine now.

Thanks !
