### ISSUE TITLE
Create AppVeyor integration build for Windows

### ISSUE THREAD

**Issue by LegalizeAdulthood** [agenium-scale/boost.simd#198]
AppVeyor is free for open source projects and integrates similarly to travis.

**Comment by jfalcou** [comment]
We had one at some point but it timed out due to d/l Boost everytime as the basic one is wrongly set.
We indeed need to put it back.

**Comment by jfalcou** [comment]
Cruising in my notes, we actually removed it as the totoal length of the test lasted more than the maximum allowed time. We're building an in house jenkins server and will push all oru test from there.
