### ISSUE TITLE
Better doc

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#215]
As soon as you want to do something a little bit advanced, it is quite difficult to find some info :)

Like I wanted to have some info on the load function arguments for indexed loading or float --> int cast.

or even this which lead to a 404 error page :)
http://numscale.github.io/boost.simd/_quick_start.html

or
http://numscale.github.io/boost.simd/tutorial-runtime.html
which is quite concise :)

Thanks !

**Comment by jfalcou** [comment]
Bunch of pages are still being revised and tutorial are being amended. 
God catch on the 404, we'll fix this.

**Comment by jfalcou** [comment]
@otristan : By indexed load, you mean gather like operations ?

**Comment by otristan** [comment]
I meant stuff like that

```
boost::simd::pack<int32_t>index {1, 2, 3, 4};
boost::simd::pack<int16_t, 8> src = boost::simd::load<boost::simd::pack<int32_t>>((const int32_t*)pSrc, index);
```

which works fine.

**Comment by otristan** [comment]
as a general note, I wouldn't mind a tutorial on what I would call type transformation.
like you got one
`boost::simd::pack<int16_t, 8>`
and you would like to transform it into two `boost::simd::pack<int32_t, 4>`
where each int16_t are "promoted" to an int32_t

I'm trying to implement a one channel audio data  short to float linear interpolation and I'm struggling a bit :)

**Comment by jfalcou** [comment]
> I meant stuff like that
> 
> ```
> boost::simd::pack<int32_t>index {1, 2, 3, 4};
> boost::simd::pack<int16_t, 8> src = boost::simd::load<boost::simd::pack<int32_t>>((const int32_t*)pSrc, index);
> ```
> 
> which works fine.

This is certainly a quirk. It works because the underlying __m128i types get converted back and forth. Are you sure the data you got inside are correct ? Moreover, unless you have a AVX2 machine, this probably generates a bunch of extract/make calls to retrieve data and set them into a single register. Not optimal I would say.

As for the other question, it's related to #17. We need a cast<U> function that fallbacks to the correct opcode sequence depending on the source and destination types. Note that casting a pack<T,N>needs to be done to a pack<U,N> thus possibly requiring multiple registers.

I can draft a small example this afternoon and tell @alankelly to add this casting issue to the tutorial lists.

**Comment by jfalcou** [comment]
Back to your piece of code, it indeed works by the fact the ctor from native storage is not explicit. I think it's a nice side effect.

**Comment by otristan** [comment]
The load results looks wrong after all. the strange thing is that even with

```
boost::simd::pack<int32_t>index {1, 2, 3, 4};
boost::simd::pack<int32_t, 4> src = boost::simd::load<boost::simd::pack<int32_t>>((const int32_t*)pSrc, index); 

```

I got the wrong result, like if indexed load didn't work correctly.

**Comment by jfalcou** [comment]
pSrc is a pointer to int32 or ?

**Comment by jfalcou** [comment]
The usual way to get from intN to int2*N is to use split.
I just discovered that for some reason, we use a different layout than for regular aggregate of registers. I'll amend split so : 

```
 pack<int16,8> x;
 pack<int32,8> y = split(x);
```

just work.

**Comment by otristan** [comment]
pSrc was an int16 pointer, but I use the trick that value N and N+1 are one after the other so I can load
indexA, indexA+1, indexB, indexB+1, ... using only a pack of indexA, indexB,...

Will check split.

Thanks !

**Comment by jfalcou** [comment]
Woudl you mind giving me a compilable (with a small bunch of meaningful data) so I can debug your issue.

As for split, until I fix it, it returns a pair so you'll have to dance a bit.

**Comment by otristan** [comment]
nevermind the issue with load. My bad. I forgot that Indexes should be divided by 2 to fully match my trick, so this won't work...

**Comment by otristan** [comment]
I would really like to see this tutorial filled with an actual content :)
http://numscale.github.io/boost.simd/tutorial-runtime.html

Thanks !

**Comment by alankelly** [comment]
We are working on getting the doc completed. I have added several more tutorials and I have some more which are almost ready. I have pushed the latest doc which is a big improvement on the old one, and I will be making regular updates and adding new tutorials in the next week or two.
Take a look here:
http://numscale.github.io/boost.simd/tutorials.html

If you have any suggestions for a tutorial, please let me know. I'm trying to make them as relevant as possible for new users. Please note that this is an on-going project, not all of the tutorials online are 100% correct, I'm working on correcting them and filling out the explanations. If you notice anything outrageous, please let me know!

**Comment by otristan** [comment]
Cool.

The actual tutorial I have mentioned seems to still be empty though :)

**Comment by alankelly** [comment]
That functionality is currently being implemented in branch: https://github.com/NumScale/boost.simd/tree/is_supported

Once it is ready and tested (should be in the next few days)., I prepare the tutorial .

**Comment by otristan** [comment]
You guys should talk as well about
BOOST_HW_SIMD_X86 redefinition
so you can activate for example avx stuff in a single file while the whole project is not compiled using it.

I suppose this is how it should be done right ?

**Comment by ccharly** [comment]
What would be your test case? Enabling only AVX for certain part while actually compiling with AVX2? The opposite is not true though as you do need to provide compiler options to enable those extension. The compiler won't be able to generate AVX2 code if your not telling it to do so.

Also, current `BOOST_HW_SIMD_X86` is always defined at the very beginning while including `boost/predef/hardware/simd/x86.h` cause this is how `boost.predef` works. Redefining it before actually including this file will lead to warning concerning redefinition of this macro.

I'm not sure we have such system to enable this, at least not with macros. Dispatching on specific extension target would be the way of doing that if you want to use SSE functions while compiling for AVX. Not sure we have this ready as well, @jfalcou may help us on that?

Tell me if I missed something from your question :)

**Comment by otristan** [comment]
It's actually the opposite I want to do.
The whole program is compiled using SSE2 because everybody got this nowadays on Intel platform
but I want to be able to use boost simd to create AVX code that I will activate at runtime if the actual processor my program currently runs on supports it.

**Comment by ccharly** [comment]
Ok, I should have read the whole topic first! ;)

We're working on those run-time (ISA) detection for now. With those helpers you'll then be able to detect SSE or AVX depending on the current processor.

Now, how about having your project compiled in both SSE and AVX (or using a library). Then you would have:  `myproject.sse`, `myproject.avx` and a `myproject` that acts like a wrapper/jumper to one of the other depending on your processor (using the run-time detection). As you already stated it before, we definitely need an example/tutorial on that.

I think you've got the basic idea and I'm pretty sure you already knew that as well.

**Comment by otristan** [comment]
having multiple project and libs is exactly the kind of stuff I would like to avoid :)
Multiple files with different #define eventually but otherwise this is really cumbersome to use.

Detecting AVX at runtime is one thing but this is quite a non issue to me as there are already ways to detect it easily (plenty of code on the web about this). Being able to use boost simd to use AVX code while not having the compiler compiling the whole program with AVX is more interesting IMHO.
Sure VS will tell me 
warning C4752: found Intel(R) Advanced Vector Extensions; consider using /arch:AVX
but hey I know what I am doing :)

**Comment by ccharly** [comment]
ahah fine. Well.. I do need to think about it a little then as this is not the way I would do that. Maybe, hacking the `BOOST_HW_SIMD_X86` may be one way, but then you'll have to hack to remove the predefs that are defined by the compiler. Let say you want to compile on `SSE*`, then you'll have to remove the `__AVX__` and `__AVX2__` before actually including of the `boost.simd` files. But maybe, this is a feature that we could implement ourselves.

Also, you seem to work with VS, then you have to use `BOOST_SIMD_ASSUME_*` to enable some SIMD extension within `boost.simd` as there is no way to enable them using the compiler options (at least for some of them).

So maybe you hack using those defines. You're setup would probably be:

``` bash
include/myproject/foo.any.hpp
include/myproject/foo.sse2.hpp
include/myproject/foo.avx2.hpp
```

With the `foo.<SIMD>.hpp` that defines the macro `BOOST_SIMD_ASSUME_<SIMD>` before actually including `foo.any.hpp`? Would this be a solution for you?

**Comment by otristan** [comment]
Well I don't really see the use case where your program is compiled using AVX flag but you would like to limit boost simd to SSE.
Or in that case you just need to declare `pack<float, 4>`

Will check BOOST_SIMD_ASSUME flags.

Thanks !

**Comment by otristan** [comment]
For what it's worth, using BOOST_SIMD_ASSUME_AVX and declaring `pack<float, 8>`
create a data with an array of two __m128 while my hack using
#undef BOOST_HW_SIMD_X86
#define BOOST_HW_SIMD_X86 BOOST_HW_SIMD_X86_AVX_VERSION
will actually use AVX.

**Comment by ccharly** [comment]
The `BOOST_SIMD_ASSUME` macros are here to workaround the lack of compiler options for MSVC. Let say you want to enable `sse4.2` with MSVC, there is actually no compiler flag to enable it. To workaround this, then you can use `/DBOOST_SIMD_ASUME_SSE4_2`. But MSVC is still able to generate this code, but there is just no way for us to detect that this is the most recent SIMD extension.

**Comment by otristan** [comment]
By the way BOOST_SIMD_ASSUME_AVX  do not exists in predef.hpp but I suppose this not an issue as
`__AVX__` is defined by VS

**Comment by ccharly** [comment]
nope, it's defined in `boost.simd` directly. Also, maybe I explained it wrong but, all `ASSUME` macros are only here to "simulate" `-msse4.1" for MSVC, as you can only specify`SSE2`,`AVX`and`AVX2`. And because we rely on compilers predefs to enable the most recent SIMD extension, we do need that kind of workaround for some extensions.

For example, if you want to use `SSE4.2` with MSVC, then you need to enable `SSE2` and define `BOOST_SIMD_ASSUME_SSE4_2`.

This is not a macro to force the SIMD extension with `boost.simd`.

**Comment by ccharly** [comment]
Using the `BOOST_HW_SIMD_X86` predef like you did is a way of forcing that, yes. Because macros such as `BOOST_SIMD_DEFAULT_SITE` and `BOOST_SIMD_DEFAULT_FAMILY` are first defined using this macro. The main problem with that is the redefinition of this macro, but if it's ok for you, then you're good. ;)

**Comment by otristan** [comment]
I don't mind not using BOOST_HW_SIMD_X86, I just don't know what is the proper way to achieve the same results.
aka using avx in boost simd without changing the whole compiler to flags AVX.
I am eager to know what would be the proper boost simd way.

Thanks !

**Comment by otristan** [comment]
Looks like what I want to do is actually not possible with LLVM so you have to rely on a .cpp per simd type  where each file is compiled with the right compiler flags :(
