### ISSUE TITLE
functions name changes

### ISSUE THREAD

**Issue by jtlap** [agenium-scale/boost.simd#22]
at the end of the migration process all selxxx functions should be renamed ifxxx
and also genmask and genmaskc,. The old names should be turnied to aliases (or not).

All this to have a more coherent naming scheme

---

After discussions tasks to do: 
- [x] remove b_ aliases
- [x] remove l_ aliases
- [x] change div\* implementation
- [x] change i\* implementation 
- [x] saturated operations decorator

**Comment by jtlap** [comment]
There are some more inconsistencies in the choice of the boost.simd functors names
Some propositions/interrogations/guidelines/rationale to be discussed are listed there

Generalities

All functor name are lower case respecting mostly separation of words by 
underscores. But not in case of separating abbreviations.

All implemented functors having the semantic of a libc++11 function
must have the same name or an alias of the same name (these name can be exceptions
to the underscore policy). These functor also admit a std_ decorator that will call 
the std:: functor.

We will speak of replacement of some functors by decorated call to other ones,
but this do not prevent to have both syntaxes. For instance

plus_s(a,b) or saturated_(plus(a,b)) and if possible  saturated_(a+b).
(saturated_ being a decorator)

# 

branching functors

All sel... and where must be removed and where
and all branching will begin by if_ or ifnot_ 

The rationale being (where aaa is a function name without underscores, 
and ccc/ddd are constant names in lowercase) :

1) all tests functors begin by if_ or ifnot_
2) if_aaa(cond,c{,d})         if cond aaa(c{,d}) is returned  else c is returned
3) ifnot_aaa(cond,c{,d})      if not cond aaa(c{,d}) is returned  else c is returned
4) if_else_ccc(cond,a)        if cond a is returned  else ccc is returned
5) if_ccc_else(cond,a)        if cond ccc is returned  else a is returned
6) if_ccc_else_ddd(cond)      if cond ccc is returned  else ddd is returned

if_add                     if_plus 
if_allbits_else
if_allbits_else_zero
if_dec  
if_else_allbits
if_else
if_else_allbits
if_else_nan                alias of if_else_allbits
if_else_zero
if_inc  
if_nan_else                alias of if_allbits_else
ifnotadd                   ifnot_plus
ifnotdec                   ifnot_dec
ifnotinc                   ifnot_inc
ifnotsub                   ifnot_minus
if_one_else_zero
if_sub                     if_minus
if_zero_else_allbits
if_zero_else
if_zero_else_one
seladd                     suppresed replaced by if_plus 
sel                        suppresed replaced by if_else 
seldec                     suppresed replaced by if_dec  
select                     suppresed replaced by if_else
selinc                     suppresed replaced by if_inc 
selsub                     suppresed replaced by if_minus

# 

predicates

they return "logical" types but can
be regular, lexicographic or reduction

1) all regular predicates must begin by is_
2) all lexicographic predicates must begin by compare_
3) reduction predicates live their lifes because they have traditional 
   well understood names (all, any, none)

modification proposed are:

are_disjoint  is_disjoint
majority      is_majoritary 

is_not_invalid           alias of is_finite

trigonometric functors

most trigonometric functors decline in 3 versions

aaa       radian version
aaad      degree version
aaapi     pi version

all version must exist when meaningfull:

acotpi, asecpi, acscpi, asecpi, atan2pi 

are missing and should be added

Perhaps deg_ and pi_ can became decorators ?

At decorator implementation times, the templated cosecant,
cosine, cotangent, sine, sinecosine, tangent are to be discussed

# 

arithmetic functors

---

Saturating operations

all saturated operators have the same name 
than the non saturating ones and the suffuix _s.

Perhaps a decorator  saturated_() or sat_() could be an alternate syntax ?

abss      abs_s
adds      add_s 
decs      dec_s
divs      divides_s
incs      inc_s
muls      multiplies_s
negs      neg_s
sqrs      sqr_s
subs      sub_s
toints    toint_s
touints   touint_s  

oneminus and oneplus are also already saturated, perhaps oneminus have to be  
desaturated one_plus be an alias of inc and have their conterparts
one_minus_s and one_plus_s (the last being an alias of inc_s)

---

i... family
the i... functors always return a result of the integral type 
associated to their first parameter. Perhaps this could be an int_()
decorator ? (not so sure)

---

div and idiv families

I am not sure that these could be changed with an internal underscore because div is an abbreviation
divceil                div_ceil  
divfix                 div_fix  
divfloor               div_floor  
divround2even          div_round2even  
divround               div_round  
idivceil               idiv_ceil  
idivfix                idiv_fix  
idivfloor              idiv_floor  
idivround2even         idiv_round2even  
idivround              idiv_round           

Perhaps ceil_, fix_, floor_, round_ and round2even_ could be decorators,
leading to:
                   round_(divides(a,b)) for divround(a,b) etc...

---

Conversions

toints         to_int_s
touint         to_uint
touints        to_uint_s
tofloat        to_float

# 

bitwise operators

They all begin by bitwise_

offer or nor b_... aliases to bitwise_... 

or turn to: they all begin by b_ 

short or clear or both?

# 

logical operators

They all begin by logical_

offer or nor l_... aliases to logical_...

or turn to: they all begin by l_ 

short or clear or both?

# 

more missing underscores

signbit         sign_bit  
signgam         sign_gam  
swapbytes       swap_bytes
tenpower        ten_power 
twopower        two_power 

the following functors do not need underscores because
they are abbreviations  

maxmag
maxnum
maxnummag
minmag
minnum
minnummag
posmax
posmin 
ulpdist

**Comment by ccharly** [comment]
Aliases may have some drawbacks. Some people may think that `b_*` and `bitwise_*` would have different meanings. `b_` could stand for boolean in some peoples mind. Even if it is well documented, at first sight, some people could be disturbed with that naming.

However, I think that some aliases **MUST** exist as they bring some good hint and are more semantic oriented. For example `if_nan_else` and `if_allbits_else` seem legit to me.

**Comment by jfalcou** [comment]
All points I don't comment on, I agree.

# trigonometric functors

most trigonometric functors decline in 3 versions
Perhaps deg_ and pi_ can became decorators ?

My Position : NO as it will make combo of decorator complex.
Either deg and pi work slike boost.Unit ad we dispatch accordingly 
OR we have a deg(x) pi(x) proxy object

# i... family

the i... functors always return a result of the integral type 
associated to their first parameter. Perhaps this could be an int_()
decorator ? (not so sure)
- [ ] My Position : This is simialr to having sum return somethign else than the type 
  it uses as input. I woudl prefer ixxx(y) to become xxx<int>(y) and use the false
  tempalte argument as a discrimiantor in dispatch

# div and idiv families

Perhaps ceil_, fix_, floor_, round_ and round2even_ could be decorators,
leading to:
                   round_(divides(a,b)) for divround(a,b) etc...
- [ ] My Position: function are now functor with proper hierarchy so :
  divides(a,b, round) is better IMHO. It also combines with the former
  poitn to make divides<int>(a,b,round)

# bitwise operators

They all begin by bitwise_ offer or nor b_... aliases to bitwise_... 
or turn to: they all begin by b_  short or clear or both?
- [x] My Position: bitwise_xxx, remove the b_

# logical operators

They all begin by logical_
- [x] My Position: logical_xxx, remove the l_

**Comment by jtlap** [comment]
I agree to all these suggestions.
Now we have to begin to enforce them as soon as the decorators are implanted or perhaps begin
by the divides enhancements which don't need decorators

**Comment by jfalcou** [comment]
starts by removing functions which must disappear then go on the divides

**Comment by jtlap** [comment]
Exactly what I am doing.

**Comment by jfalcou** [comment]
Are we done with this @jtlap ?
