### ISSUE TITLE
split behavior

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#224]
Hi,

Using the following code

```
boost::simd::pack<float, 8> srcF { 0.f, 1.f, 2.f, 3.f, 4.f, 5.f, 6.f, 7.f };
auto s = boost::simd::split(srcF);
```

s is of type 
`std::pair<boost::simd::pack<double, 4>, boost::simd::pack<double, 4>>`
shouldn't it be of type
 `std::pair<boost::simd::pack<float, 4>, boost::simd::pack<float, 4>>`

Thanks !

**Comment by jfalcou** [comment]
No. Split cut and upgrade the type. The function that take a vector and slice it in two part of the type (but then of half the cardinal) is slice.

Slice is used whenever you can beneit from an udnerlying smaller ISA.
Split is the abstraction over the common "promote the type to the next biggest and update cardinal accordigly".

On Intel, split is calling one of _mm_unpack\* intrinsics.

**Comment by otristan** [comment]
Brilliant !
Much appreciated.

**Comment by jfalcou** [comment]
As of now, split returns an array instead of a pair. So code like : 

```
 pack<int8,N> x;
 pack<int16,N> y = split(x);
```

should be working directly.
