### ISSUE TITLE
prefetch read/write

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#225]
There used to be a prefetch_read and prefetch_write.
Are those deprecated or maybe not useful after all ?

Thanks !

**Comment by jfalcou** [comment]
They were not ported from the old version yet. We have to think a bit over the API.
If you look at the old version, masked load required an additional parameter. This has been changed to use a mask(ptr) wrapper. We're debating if prefetch(ptr) is not a better interface.

This will probably be done for after the 1.0 Release Candidate.

**Comment by jfalcou** [comment]
Next to that, I'm also eager to get a reproducible, small self contained sample that show the benefit. Hardware prefetcher being what they are, it's rather complicated to get something noticeable.

**Comment by otristan** [comment]
This was more a pedantic question. I never was able either to notice a difference
