### ISSUE TITLE
(de)interleave aggregate functions

### ISSUE THREAD

**Issue by jfalcou** [agenium-scale/boost.simd#227]
<see later>

**Comment by jfalcou** [comment]
Askign mostly for @alankelly @jtlap @timblechmann

**Comment by jtlap** [comment]
as you prefer

**Comment by alankelly** [comment]
So, after doing more tutorials and benching them to ensure correct performance, I discovered some interesting details for deinterleave_first/second, which probaly map to the other interleaves. On SSE, these functions map to an intrinsic. However, on AVX, the vector must first be split into two SSE vectors. So, a common operation for a user might be deinterleave-first followed by second. In this case, I'm splitting the same AVX vector into two SSE vectors twice, taking almost twice as long as necessary. This is clearly unnecessary, therefore I propose that we add de/interleave_both which returns a tuple of vectors.

**Comment by jfalcou** [comment]
86f11ad173b83d9114b16c0012b59facc69bb817 adds a mutual deinterleave functions
A mutual interleave functions will added soon

**Comment by jfalcou** [comment]
916cc96 adds mutual interleave
