### ISSUE TITLE
Add benchmarks against basic SIMD library

### ISSUE THREAD

**Issue by jfalcou** [agenium-scale/boost.simd#228]
- [ ] Agner Fog
- [ ] Eigen
- [ ] Vc
- [ ] Yepp

**Comment by superbobry** [comment]
Do you have a specific benchmarking library in mind (e.g. [google/benchmark](https://github.com/google/benchmark))?

**Comment by jfalcou** [comment]
We have an in-house bench system (ns.bench) because we wante to limit dependencies.
