### ISSUE TITLE
Predef(s) are wrong

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#245]
As @jfalcou told me, there is some strange errors while compiling with avx2 as it seems that the compiler is not able to force inline functions like `fma` and that's all because `-mfma` is not implicitly added if `-mavx2` is provided on the compiler command line.

This means that we were wrong when we added SIMD detection in `boost.predef`.  Using this simple example, we can see that `SSE4a`, `XOP`, `FMA4` and `FMA3` are not added with `-mavx2`:

``` cpp
#include <iostream>

int main() {
    #define SAY(what) std::cout << what << std::endl

    #if defined(__MMX__)
    SAY("MMX");
    #endif

    #if defined(__SSE__) || defined(_M_X64) || _M_IX86_FP >= 1
    SAY("SSE");
    #endif

    #if defined(__SSE2__) || defined(_M_X64) || _M_IX86_FP >= 2
    SAY("SSE2");
    #endif

    #if defined(__SSE3__)
    SAY("SSE3");
    #endif

    #if defined(__SSSE3__)
    SAY("SSSE3");
    #endif

    #if defined(__SSE4A__)
    SAY("SSE4a");
    #endif

    #if defined(__SSE4_1__)
    SAY("SSE4.1");
    #endif

    #if defined(__SSE4_2__)
    SAY("SSE4.2");
    #endif

    #if defined(__AVX__)
    SAY("AVX");
    #endif

    #if defined(__FMA4__)
    SAY("XOP");
    #endif

    #if defined(__FMA4__)
    SAY("FMA4");
    #endif

    #if defined(__FMA__)
    SAY("FMA3");
    #endif

    #if defined(__AVX2__)
    SAY("AVX2");
    #endif

    return 0;
}
```

Results:

`-mavx2`:

```
MMX
SSE
SSE2
SSE3
SSSE3
SSE4.1
SSE4.2
AVX
AVX2
```

`-mfma`:

```
MMX
SSE
SSE2
SSE3
SSSE3
SSE4.1
SSE4.2
AVX
FMA3
```

`-mfma4` or `-mxop`:

```
MMX
SSE
SSE2
SSE3
SSSE3
SSE4a
SSE4.1
SSE4.2
AVX
XOP
FMA4
```

As we can see, `avx2` does not imply any of `sse4a`, `fma4`, `fma3`, `xop`. So the assumption that was made before is no longer true in `boost.predef` and because in the current implementation of `boost.simd`, we use the following extensions hierarchy for `avx2`:

``` cpp
struct avx2_  : fma3_ { using parent = fma3_; };
```

Which is only true only if `-mavx2` and `-fma` are provided to the compiler options.

Maybe we should fix this and exclude those options from the "native" SIMD extensions chain of predef? Then we could use them as:

``` cpp
#if BOOST_HW_SIMD_X86_FMA3
...
#endif
```

But no longer as:

``` cpp
#if BOOST_HW_SIMD_X86 == BOOST_HW_SIMD_X86_FMA3_VERSION
...
#endif
```

Which means that all `*_VERSION` will be gone for `sse4a`, `fma4`, `fma3, and`xop`.

WDYT?

**Comment by jfalcou** [comment]
Fixed by  004dc94
