### ISSUE TITLE
add aligned_array

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#257]
my 2 cents on an issue which I suppose will happen to other person

Would be great if you guys can add an aligned_array for stack allocated array with a required alignement (> max_align_t) as alignas currently do not work in struct allocated with new with over aligned datas

A simple struct which allocate more data and align it manually in the ctor for example

example (in that case alignas won't currently work)

```
struct A
{
 aligned_array<float, 128, 32> data;
}

int main(void)
{
std::scoped_ptr<A> a;
return 0;
}
```

**Comment by jfalcou** [comment]
We add one before in NT2 and it was basically a copycat of std array + alignment.
The question is : is it Boost.SIMD responsability or Boost.Align or Boost.Array ?

In C++11, isn't it possible to just use alignof on a std:array instance ?

**Comment by otristan** [comment]
it could indeed be added in boost align 

alignas and other c+11 alignement won't currently work 
see
http://stackoverflow.com/questions/15511909/alignas-specifier-and-new-c11

**Comment by jfalcou** [comment]
I think if you push a PR on Boost.Align on that, we'll gladly push for it t be accepted. :)

We just think we should not duplicate alignment related feature of Boost.Align.

**Comment by ccharly** [comment]
As long as I remember, the maintainer of `boost.align` didn't want to add this into its module. Maybe we could try to add this into `boost.array` instead?

**Comment by otristan** [comment]
Or just wait for this :)
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3396.htm

**Comment by jfalcou** [comment]
@otristan what do we do with this issue then ? Do you want me to port it over Boost.Align Issues ?

**Comment by otristan** [comment]
I will close it and wait for a mature C++17 support :)
