### ISSUE TITLE
combine on scalars

### ISSUE THREAD

**Issue by timblechmann** [agenium-scale/boost.simd#26]
the following code compiles:
`pack<float, 4> x = combine( pack<float, 2>(0.f), pack<float, 2>(0.f) );`

but trying to do the same with scalars fails:
`pack<float, 2> y = combine( 0.f, 0.f );`

likewise, one-element packs are not allowed:
`pack<float, 2> x = combine( pack<float, 1>(0.f), pack<float, 1>(0.f) );`

this makes it a bit troublesome to generic write code that supports both scalar and vector types ...

**Comment by timblechmann** [comment]
use case: https://github.com/timblechmann/nova-nt2-ugens/blob/xfade/dsp/parabol_sine.hpp

**Comment by jfalcou** [comment]
That's something we have on our radar for the new version :) Will keep your use case in mind when we get there.

**Comment by timblechmann** [comment]
:D

**Comment by jfalcou** [comment]
@timblechmann  : are we still OK that `pack<T,1> != T` ?

**Comment by timblechmann** [comment]
@jfalcou what exactly do you mean? a lot of my code is based on the idea that the same code for scalars should also work for packs ... in some cases scalars are combined to `pack<float, 2>`, though `pack<float, N>` should be combined to `pack<float, 2*N>` ...

**Comment by jfalcou** [comment]
I mean that `pack<T,1>` is _not_ an alias of `T.` It's a regular pack type following pack API but containing a single value.

**Comment by timblechmann** [comment]
ah ... as in `pack<float, 1>`? yes, that's fine ... though sometimes it would be nice to have for generic code (i'm currently using a metafunction to select the pack type or the scalar https://github.com/timblechmann/nova-nt2-ugens/blob/xfade/dsp/utils.hpp#L45)

**Comment by jfalcou** [comment]
`pack<T,1>` naturally comes out when dealing with 64bits NEON so we may need them but they're not `T`. 

This may means we need something like your `as_pack` but with a different name then.

**Comment by jfalcou** [comment]
ok, so this point came again when we were looking and combine/slice. We wanted to be able to return the most natural type from slice so we avoid convertion etc... The following happens : 
- you slice a `pack<T,N` which is emulated as array of scalar OR is natively stored. You end up with two `pack<T,N/2>` which are also scalar-emulated. The natural return for slice is then an  `array<pack<T,N/2>,2>` This may end up giving a  `pack<T,1>` inside.
- you slice a  `pack<T,N>` which is stored as an aggregate of the general form of `array<pack<T,N/P>,P>`. If P is equals to 2, we return the storage directly (no additional copy). If not, we recombine them somehow intot the proper array.

So `pack<T,1>` is a legit type to have so we don't have to go through hoops when dealing with slice and combine. So the question is, what should now `as_pack<T,1>`does ?

**Comment by jfalcou** [comment]
The combine(scalar,scalar) have been merged in 160d8c9f081ee174a2537c500eb112d5802df014
The pack<T,1> should be working but another PR will bring more tests to check that.
