### ISSUE TITLE
Compile issue on 32 bits OSX

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#263]
When trying to compile some code in 32 bits on OSX, I have an error
`/usr/local/include/boost/simd/arch/x86/sse2/simd/function/extract.hpp:75:14: error: use of undeclared identifier '_mm_cvtsi128_si64'`

This intrinsincs is only declared on x64 architecture in emmintrin.h

```
#ifdef __x86_64__
static __inline__ long long __attribute__((__always_inline__, __nodebug__))
_mm_cvtsi128_si64(__m128i __a)
{
  return __a[0];
}
#endif
```

Currently this version of extract is removed on MSVC but it should probably be removed when building 32 bits application as well

Thanks !

**Comment by otristan** [comment]
By the way, it's available on MSVC
https://msdn.microsoft.com/en-us/library/bb531384(v=vs.120).aspx
So the define should probably only be about x64 build

**Comment by jfalcou** [comment]
I guess using #ifdef **x86_64** around it is enough ?

**Comment by otristan** [comment]
Works fine now.

Thanks !
