### ISSUE TITLE
__vectorcall advised ?

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#264]
Hi,

I found older reference to use __vectorcall calling convention when building boost simd.
Is this still advised or something from the past ?

Thanks !

**Comment by ccharly** [comment]
As long as I remember, before MSVC 2015, it was flaky. With the latest update of MSVC 2015, it may fix of some performance issues (like passing really large number of packs as parameters to a function). The optimizer is becoming better and better and this is mostly non-useful for now.

You can still use it as it may improve performance, but this is really context dependent. So you have to test both with and without. It should not have any ill effects.

**Comment by otristan** [comment]
From my first test, it looks like to be worse using it.

Thanks for the hint !
