### ISSUE TITLE
functions input parameters improvements

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#272]
Hi,

Following changes regarding function like split returning an array.
Would it make sense to allow functions with two inputs to use this returns as input as well ?

So you could do something like that

`auto arr = deinterleave(split(src))`

instead of

```
auto a = deinterleave_first(split_low(src16), split_high(src16));
auto b = deinterleave_second(split_low(src16), split_high(src16));
```

or

```
auto arr = deinterleave(split_low(src16), split_high(src16));
```

Thanks !

**Comment by jfalcou** [comment]
Shoudln't it be handled by cast ? the array of 2 packs is somehting that should travel as a pack of proper size, the current situation being a temporary fix.

**Comment by otristan** [comment]
Whatever works :)

My main goals are performance and readability

**Comment by jfalcou** [comment]
With cast, the current code should become : 

```
auto a = deinterleave( cast<int32_t>(src16));
```

where cast actually calls split and shove it into a proper pack that get deinterleaved properly later.
So I guess we an end up with the same performances.

**Comment by otristan** [comment]
I'll try that when cast will be available then.

Thanks !
