### ISSUE TITLE
Assigning values to packs is not supported

### ISSUE THREAD

**Issue by hkaiser** [agenium-scale/boost.simd#274]
Assigning scalar values to a pack instance is currently not supported:

```
pack<int> p;
p = 42;
```

This makes it difficult to be used in generic code. The effect should be to assign the value to all members of the pack.

**Comment by jtlap** [comment]
However pack < int >  p(42);  
already works

**Comment by hkaiser** [comment]
@jtlap absolutely, so does this: `p = pack_t(42)`

**Comment by hkaiser** [comment]
Thanks! Works like a charm.
