### ISSUE TITLE
use of C++11 cmath

### ISSUE THREAD

**Issue by jtlap** [agenium-scale/boost.simd#28]
from c++11 cmath garantees implementation of a bunch of our functions in std::

In think we have 

1) to provide access to these function by a call style toto(x, std_) that will call std::toto(x) 
1) to bench these functions against our scalar versions

**Comment by jfalcou** [comment]
wasn't that the std external module was doing ?

**Comment by jtlap** [comment]
yes, but now its easier to add a tag and there is no external boost.simd 
module...

**Comment by jfalcou** [comment]
yes OK then.
