### ISSUE TITLE
benches does not compile with clang when g++6 is installed

### ISSUE THREAD

**Issue by jtlap** [agenium-scale/boost.simd#280]
even with clang 3.9 which needs stdlibc++ 6 !

I don't even know if they compile when g++-6 is not installed, but the error appears in the library
__and_ ... has no ::value

**Comment by ccharly** [comment]
well.. I don't really get it. Is this really related to our benches? It seems that is a user installation problem instead? I didn't try to compile them using the same setup but I don't see what we are going to do if compiler complains about whatever internal errors it has because it is messing up with other compiler includes?

Anyway, I'll give it a shot whenever I have time to do so.

**Comment by jfalcou** [comment]
Let's fix this later, it's more a system issue than an issue with our code base.

**Comment by ccharly** [comment]
Actually I've been digging into this issue to make sure it was a system issue but actually it's not.

This is a bug in clang which when using headers from gcc 6+ (I guess, not sure for that). Anyway, whenever you try to use a `std::tuple` with a single element and default constructs it, you have that error:
```
#include <tuple>

int main() {
  std::tuple<int> t;
  return 0;
}
```

You get the following error:
```
In file included from main.cpp:1:
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:483:62: error: pack
      expansion contains parameter packs '_Elements' and '_UElements' that have different lengths
      (1 vs. 0)
      return __and_<is_constructible<_Elements, _UElements&&>...>::value;
                                     ~~~~~~~~~  ~~~~~~~~~~   ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:631:21: note: in
      instantiation of function template specialization 'std::_TC<true, int>::_MoveConstructibleTuple<>'
      requested here
                    _MoveConstructibleTuple<_UElements...>()
                    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:636:19: note: while
      substituting prior template arguments into non-type template parameter [with _UElements = <>]
        constexpr tuple(_UElements&&... __elements)
                  ^~~~~
main.cpp:4:19: note: while substituting deduced template arguments into function template 'tuple' [with
      _UElements = <>, $1 = (no value)]
  std::tuple<int> t;
                  ^
In file included from main.cpp:1:
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:489:60: error: pack
      expansion contains parameter packs '_UElements' and '_Elements' that have different lengths
      (0 vs. 1)
      return __and_<is_convertible<_UElements&&, _Elements>...>::value;
                                   ~~~~~~~~~~    ~~~~~~~~~ ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:633:21: note: in
      instantiation of function template specialization 'std::_TC<true,
      int>::_ImplicitlyMoveConvertibleTuple<>' requested here
                    _ImplicitlyMoveConvertibleTuple<_UElements...>()
                    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:636:19: note: while
      substituting prior template arguments into non-type template parameter [with _UElements = <>]
        constexpr tuple(_UElements&&... __elements)
                  ^~~~~
main.cpp:4:19: note: while substituting deduced template arguments into function template 'tuple' [with
      _UElements = <>, $1 = (no value)]
  std::tuple<int> t;
                  ^
2 errors generated.
```

I'm using `clang-3.5` with `gcc-6.2` installed. I'm probably gonna find a workaround in `ns.bench` to fix that.

**Comment by ccharly** [comment]
Here is one bug that causes the error: https://llvm.org/bugs/show_bug.cgi?id=14858

**Comment by ccharly** [comment]
Ok, I've workaround this bug in `ns.bench` now. I've created a new branch and gonna create a PR for that. @jtlap could you please re-bench everything that was not working with your `clang` and report me if something is still not working? Thanks. :)

**Comment by ccharly** [comment]
https://github.com/NumScale/boost.simd/pull/366

**Comment by jfalcou** [comment]
Does #366 make this closed ?

**Comment by jtlap** [comment]
now it seems to compile with my clang 3.9.
I think the issue can be closed
