### ISSUE TITLE
copysign not optimal

### ISSUE THREAD

**Issue by timblechmann** [agenium-scale/boost.simd#31]
it seems that copysign is defined as:
`bitwise_or(bitofsign(a1), boost::simd::abs(a0));`

while afaict it could be simplified to:
`bitwise_or(bitofsign(a1), a0);`

or am i missing something?

**Comment by jtlap** [comment]
Le 05/12/2015 14:05, Tim Blechmann a écrit :

> it seems that copysign is defined as:
> |bitwise_or(bitofsign(a1), boost::simd::abs(a0));|
> 
> while afaict it could be simplified to:
> |bitwise_or(bitofsign(a1), a0);|
> 
> or am i missing something?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jfalcou/boost.simd/issues/31.
> 
> it's a1 with the sign of a0.
> if a1 if negative and a0 positive your formula is wrong as the result 
> must be positive.
> But it is possible that the formula is not optimal.

   J.T.. Lapresté

**Comment by jfalcou** [comment]
Isn't it a xor then or some other bit tricks ?

**Comment by jtlap** [comment]
Le 05/12/2015 15:38, Joel Falcou a écrit :

> Isn't it a xor then or some other bit tricks ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jfalcou/boost.simd/issues/31#issuecomment-162197543.
> 
> no because the sign of a0 replace the sign of a1

I have no bitreplace available, but perhaps we can write one.

```
      J.T.L.
```

**Comment by timblechmann** [comment]
ah, stupid me ... you're totally right, sry for the noise
