### ISSUE TITLE
Is this worthy to use this library ?? or Am I wrong to use this ??

### ISSUE THREAD

**Issue by markyang59** [agenium-scale/boost.simd#323]
windows 10, VS2015, 64bit, release
I wrote sample code to test performance of this lib
but result is disappointing. 
Performance gain is so small..
normal calc takes 200 ms,
SIMD calc takes     195 ms,
on my old PC
Is there any problem in my code ?
or This lib have in nature limitation ??

    int main()
    {	
	    uint64_t size = 500000000;
	    int32_t* data = new int32_t[size];
	    for(uint32_t i=0;i<size;i++) data[i]=i;
	    int32_t  sum  = 0;
	    int32_t  i    = 0;

	    cputime_init();
	    uint64_t t1 = 0;
	    uint64_t t2 = 0;
	    uint64_t diff = 0;

	    // normal
	    t1 = cputime_get();
	    for(i=0;i<size;i++)
   	    {
		    sum += data[i];
	    }
	    t2 = cputime_get();
	    diff = t2 - t1;
	    cout<<"Normal Sum: "<<sum<<"       Time:"<<diff<<endl;

	    // SIMD
	    t1 = cputime_get();
	    using pack_t = boost::simd::pack<int32_t>;
	    int32_t cardinal = pack_t::static_size;
	    i = 0;
	    pack_t p_data;
	    pack_t p_sum{0};
	    for(i=0;i<size;i+=cardinal)
	    {
		    p_data = boost::simd::load<pack_t>(data + i);
		    p_sum += p_data;
	    }
	    int32_t sum2 = 0;	
	    for(;i<size;i+=1)
	    {
		    sum2 += data[i];
	    }	
	    int32_t* ret = new int32_t[cardinal];
	    boost::simd::store(p_sum,ret);
	    for(int32_t i=0;i<cardinal;i++)
	    {
		    sum2 += ret[i];
	    }

	    t2 = cputime_get();
	    diff = t2 - t1;
	    cout<<"SIMD   Sum: "<<sum2<<"       Time:"<<diff<<endl;
	    delete ret;
	    delete data;

	    _getch();

	    return 0;
    }

**Comment by ccharly** [comment]
hello,

There are multiple things to say about your example:
- First, your data are not aligned, which may cause small loss of performance on some machines
- Summing floating point values across a block of data which size is of constant size that can be inferred by the compiler is usually trivially autovectorized by most modern compilers. Looking at the assembly of your code shows that it is exactly what happens
- MSVC is rather limited in the way you can specify SIMD instruction set. Look [there](http://developer.numscale.com/boost.simd/current/quickstart.html) (the `BOOST_SIMD_ASSUME_*` part to see how `boost.simd` let you define that properly.

Using your code and fixing those small issues and doing something more computationally intensive like sum of sqrt leads us to a speedup of x3 to x6 depending on the SIMD instruction set used.

Remember that SIMD instructions are better when the arithmetic density of the computation is high enough. To conclude, it's not like we don't win much but more like what we're doing is on par with the autovectorized code. As soon as you will start writing more complex code, the library's effectiveness will be more evident.

I would advise you to take a look at more of the [documentation](http://developer.numscale.com/boost.simd/current/modules.html),  especially at the `boost::simd::accumulate` helper.

**Comment by markyang59** [comment]
Thank you for clear explanation.
Means it will be worthy to tinkering with this lib.
I will try..
