### ISSUE TITLE
invalid function inlining (MSVC)

### ISSUE THREAD

**Issue by thrunduil** [agenium-scale/boost.simd#347]
I am testing simd library using VS 2015 on an architesture with AVX2 and FMA3 instructions, with /Ox, /Oi, /Ot optimization flags, for AVX2 architecture, using precise floating point model.

Visual Studio has huge problems with inlining functions. Apparently there are missing BOOST_FORCEINLINE clues. For example after enforcing total inlining of sin functions increased performance nearly 7 times in double precision (from 2x slower than std::sin to 3.5x faster).

Functions not inlined:
1. std::forward
2. functions in if_else.hpp file
3. brigand::real_::operator value_type() const
4. std::bitset<4>::all()

Similarly for log function, simd version is about 1.5x faster than std::log, but after enforcing total inlining is about 7x faster. In this case all problems are caused by std::pairs. VC is not able to inline any function, that returns this type (forceinline does not help, std::pair must be explicitly casted to some pod type).

This library is very fast. However VS is not able to optimize code properly and overall performance of the library is a little disapointing. I think, that solving this inlining issues would greatly improve this library on Windows.

Additionally function sin does not compile with fast floating point model, error message:
error C2923: 'boost::simd::detail::trig_reduction': 'degree_tag' is not a valid template type argument for parameter 'unit_tag'.

**Comment by jfalcou** [comment]
Hi and thanks for your input !

As far as the force-inlining goes, I think we can fix : 

 - functions in if_else.hpp file
 - brigand::real_::operator value_type() const

For the rest, I think we need to either provide a replacement for std::forward but bitset will be a bit of an issue. Maybe we cna contact some Microsoft guys and see how they can improve this.

**Comment by jfalcou** [comment]
As for pair, I guess having a small pseudo-pair type force-inlined locally and compatible with std::get is maybe enough.

**Comment by jfalcou** [comment]
if_else looks to be fixed now

**Comment by jfalcou** [comment]
and for brigand : https://github.com/edouarda/brigand/issues/225
Meanwhile I'll fix locally

**Comment by jfalcou** [comment]
For bitset, the fix can be to use bitset::all in the cases where we know we're forced to (ie N> 64) and use .value() == Valmax in other cases

**Comment by jfalcou** [comment]
@thrunduil would you mind telling me if the fix of inline on if_else has any impact.
I'll push a pair of branch to solve the other issue (forward & bitset usage) soon on which I would like your input later on.

**Comment by jfalcou** [comment]
FORCEINLINE brigand::real_ has been taken care of locally for now.

**Comment by jfalcou** [comment]
@thrunduil we've reimplemented hmsb and related tools so now the codegen should be better for all functions using all().
