### ISSUE TITLE
AVX512 support

### ISSUE THREAD

**Issue by jeffamstutz** [agenium-scale/boost.simd#362]
Is AVX512[KNL, SKX] planned, and if so, on what timeline?

Very nice library, BTW!

**Comment by jfalcou** [comment]
Thanks for your interest :)

AVX512 support is currently available via a licence of bSIMD, the closed source product Boost.SIMD is extracted from. You can contact us at contact@numscale.com if you're interested.

**Comment by jeffamstutz** [comment]
Great, I may email you with further questions. :)
