### ISSUE TITLE
Problems compiling on Arch

### ISSUE THREAD

**Issue by jeffamstutz** [agenium-scale/boost.simd#363]
When including ```boost/simd/arithmetic.hpp```, I get the following compile errors (gcc-6.2.1 and gcc-5.4.0, both from Arch linux package manager, clang-3.9.1 on the same machine works):

[  3%] Built target ospray_common
[ 43%] Built target ospray
[ 44%] Built target ospTutorial
[ 45%] Built target ospTutorialC
[ 46%] Building CXX object builddir/modules/intel64/cpp_renderer/CMakeFiles/ospray_module_cpp.dir/camera/PerspectiveN.cpp.o
In file included from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/function/scalar/rsqrt.hpp:18:0,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/function/rsqrt.hpp:51,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/arch/common/scalar/function/sqrt.hpp:19,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/function/scalar/sqrt.hpp:14,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/function/sqrt.hpp:44,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/arch/common/scalar/function/hypot.hpp:29,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/function/scalar/hypot.hpp:14,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/function/hypot.hpp:55,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/arithmetic.hpp:197,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/camera/../common/simd.h:21,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/camera/../common/RayN.h:20,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/camera/CameraN.h:20,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/camera/PerspectiveN.h:19,
                 from /home/jamstutz/src/ospray/modules/cpp_renderer/camera/PerspectiveN.cpp:18:
/home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/arch/x86/sse1/scalar/function/rsqrt.hpp: In member function ‘A0 boost::simd::ext::impl_rsqrt_<boost::simd::sse1_, boost::simd::pedantic_tag, boost::dispatch::scalar_<boost::dispatch::single_<Origin> > >::operator()(const boost::simd::pedantic_tag&, const A0&) const’:
/home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/arch/x86/sse1/scalar/function/rsqrt.hpp:96:36: error: ‘Smallestposval’ was not declared in this scope
       auto is_den = bs::abs(a00) < Smallestposval<A0>();
                                    ^~~~~~~~~~~~~~
/home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/arch/x86/sse1/scalar/function/rsqrt.hpp:96:53: error: expected primary-expression before ‘>’ token
       auto is_den = bs::abs(a00) < Smallestposval<A0>();
                                                     ^
/home/jamstutz/src/ospray/modules/cpp_renderer/include/boost/simd/arch/x86/sse1/scalar/function/rsqrt.hpp:96:55: error: expected primary-expression before ‘)’ token
       auto is_den = bs::abs(a00) < Smallestposval<A0>();
                                                       ^

I get a lot more of the same errors, seems to be just an issue with `Smallestposval`. As noted above, using clang-3.9.1 installed from the Arch package manager, things compile just fine (using ```-stdlib=libstdc++```, BTW).

**Comment by jeffamstutz** [comment]
FWIW, If you want a full reproduce using my original source, I am building OSPRay (devel branch: https://github.com/ospray/OSPRay), with this repo cloned in the "modules" directory (jda/simd branch: https://github.com/jeffamstutz/module_cpp_renderer)

Cheers,
Jeff

**Comment by jfalcou** [comment]
Looks like a simple case of missing include files. Try to see if adding the include for Smallestposval  Zero and Inf in `boost/simd/arch/x86/sse1/scalar/function/rsqrt.hpp` fixes your issue : 

    #include <boost/simd/constant/smallestposval.hpp>
    #include <boost/simd/constant/zero.hpp>
    #include <boost/simd/constant/inf.hpp>

**Comment by jeffamstutz** [comment]
That does, indeed, fix the problem. Thanks!

**Comment by jfalcou** [comment]
Lemme fix that in develop then

**Comment by jeffamstutz** [comment]
Perfect....strange that it didn't show up w/ clang.

**Comment by jfalcou** [comment]
Probably means that clang includes different file in different order for some reason.
We strive to fix those incomplete include issues but some creep up nonetheless.
