### ISSUE TITLE
Error in doc introduction?

### ISSUE THREAD

**Issue by AntoineD** [agenium-scale/boost.simd#364]
At the `boost::simd::transform` examples in https://developer.numscale.com/boost.simd/documentation/develop and doc/examples/addvector.cpp, it seems the `data` array comes from nowhere.

**Comment by jfalcou** [comment]
probably should be data0. Good catch.
@alankelly can you confirm and fix ?

**Comment by alankelly** [comment]
This has been fixed. The online doc will change the next time we update it
