### ISSUE TITLE
Full complex types integration

### ISSUE THREAD

**Issue by jfalcou** [agenium-scale/boost.simd#369]
Provide a `boost::simd::complex<T>` class that behaves properly as a representation of complex number whenerver T is a scalar or a pack

- consider reuse builtin complex functions on gcc/clang in the scalar cases
- ensure `complex<pack<float>>` is working generically
- modernize API w/r to what `std::complex<T>` provides

**Comment by lesshaste** [comment]
What happened to this proposal? Currently GCC and Clang do a terrible job autovectorizing complex arithmetic and most people don't want to hand code simd solutions so any help boost.simd could give would be great.

**Comment by jfalcou** [comment]
We're currently revising the scope and roadmap of the open part of bSIMD so expect this issue to be roadmapped and given a timeline of integration a bit later.
