### ISSUE TITLE
Add functions for load/store scalar sse mode

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#4]
For loading, on MSVC 32-bit it is better to use _mm_load_ss, on other platforms it's better to use _mm_set_ss.
Likewise, _mm_store_ss or _mm_cvtss_f32 for storing.

[original issue here](https://github.com/jfalcou/nt2/issues/667).

**Comment by jfalcou** [comment]
Should we do this OR shoudl it be tied to pack<T,1> post-ABI rework ?

**Comment by jfalcou** [comment]
COnsidering lack of interest and low priority I'm closign this until someone express interest.
