### ISSUE TITLE
user defined literals usage

### ISSUE THREAD

**Issue by aminiussi** [agenium-scale/boost.simd#404]
Hi,
Not a biggie but in include/boost/simd/litteral.hpp, why two 't'.
If a PR is submitted, (if only to take BOOST_NO_CXX11_USER_DEFINED_LITERALS into account) should backward compatibility be preserved ? 

Thanks

**Comment by jfalcou** [comment]
Those includes are in test so in fact, you can just wrap the test inside this BOOST macro.
Normally, no internal file shoudl include literral.hpp

The double t is a stupid mistake and should be fixed yes.

**Comment by aminiussi** [comment]
PR #405
