### ISSUE TITLE
using all any & none as decorators

### ISSUE THREAD

**Issue by jtlap** [agenium-scale/boost.simd#409]
compare_equal and compare_notequal are in the "compare" family of lexicographic comparison, 
but are in fact not really linked with lexicographical order in any way.

compare_(not)equal could be aliased with all_(not)equal, to be more understandable and so 
more usable, but in fact I propose another solution.

I propose to add three "horizontal" decorators

all_
any_
none_

(the name can be discussed)

These decorators could be applied to any functor returning
an simd vector (or only to predicates (?)), with the obvious meaning.

in general xxx_(yyy)(...) (where xxx_ is one of the three decorators and yyy any 
Boost.simd functor) would be equivalent to xxx(yyy(...)), but there are
cases where  xxx_(yyy)(...) can be optimized (peculiarly in altivec which have 
vec_all_lt  vec_all_gt etc.) 

Joel told me that there was already this idea turning in some brains. What do you think ?

**Comment by jfalcou** [comment]
I think we can just reuse all/any/none directly as we can dispatch `all(callable object) `easily to the `compare_???` functions.

We should also consider renaming `compare_less` to `is_lexicographic_ordered` or something ?

**Comment by jtlap** [comment]
we close or do something about the last item ?

**Comment by jfalcou** [comment]
the issue is open but not a priority right now. Let finish the work on complex and ranges first.
