### ISSUE TITLE
segmented_output_range

### ISSUE THREAD

**Issue by aminiussi** [agenium-scale/boost.simd#422]
The interface of that function comes un 4 flavors
- range, with and without explicit type size
- iterator pair, with and without explicit type size

the one with explicit type size are problematic for at least one compiler (intel 15..) and they seems to be 'implementation' version (only supposed to be called through the ones without the sizes).
If correct, would it be ok to put them in the detail namespace ? that would make overload resolution easier.

**Comment by jfalcou** [comment]
Nope, they are in the public API cause you may want to segment your range using pack of arbitrary cardinal for unrolling purpose. The issue with overloading on icpc looks more related to the decltype usage of the non-sized ones. Maybe putting the return type computation in a separate box is better.

**Comment by aminiussi** [comment]
I'll try, but putting those in different namespace and leaving the decltype based prototypes in the simd namspace gets the compilation and test passing (I guess just rename the explicit size version would do).

> no instance of overloaded function "segmented_input_range" matches the argument list
>             argument types are: (std::vector<int8_t, boost::simd::allocator<int8_t, 16UL>>)
>     auto pr = segmented_input_range(ref);

**Comment by aminiussi** [comment]
But who know... massaging the return type seem to do some good...

**Comment by aminiussi** [comment]
PR #424 contains modified code which is Intel 15 freindly.
I spited the doc between the function and the tuple type.
