### ISSUE TITLE
Make transform and other algorithms cardinal aware

### ISSUE THREAD

**Issue by jfalcou** [agenium-scale/boost.simd#426]
Make it so `transform` can be called with an arbitrary cardinal passed either as a constant OR fetched from an arch obejct like `sse2_`

**Comment by jfalcou** [comment]
Current tested API @aminiussi  is 

`simd::transform(b,e, d, func, 4_c)` using litteral for integral_constant

is it ok for you ?

**Comment by aminiussi** [comment]
Hi,
Sorry but our cluster has been down and I won't have access to it before next week.
I'll test it then.
thks

**Comment by aminiussi** [comment]
Znort! so the compiler does not support the user defined type spec of literals.

**Comment by aminiussi** [comment]
> In file included from /scratch/alainm/view/boost.simd/test/doc/range/segmented_aligned_range_card.cpp(11):
> /scratch/alainm/view/boost.simd/include/boost/simd/literal.hpp(46): error: expected an operator
>       constexpr nsm::uint64_t< boost::simd::detail::parse<sizeof...(c),c...>(1)> operator"" _c()
>

**Comment by jfalcou** [comment]
After a while, I think somethign else has to be able to do this instead of the basic algorithm. Closing this and will try to get a better design
