### ISSUE TITLE
include dependencies

### ISSUE THREAD

**Issue by aminiussi** [agenium-scale/boost.simd#428]
The following code does not compile due to include order:
```
#include <boost/simd/arch/common/simd/function/shuffle/repeat.hpp>

int main() {
  boost::simd::detail::is_repeat<-3, 0, -2, -1> r;
}

```

The include sequence being:
> In file included from ./include/boost/simd/arch/x86/sse1/simd/function/shuffle.hpp(12),
>                  from ./include/boost/simd/function/simd/shuffle.hpp(17),
>                  from ./include/boost/simd/function/shuffle.hpp(233),
>                  from ./include/boost/simd/arch/x86/sse2/simd/function/is_eqz.hpp(15),
>                  from ./include/boost/simd/function/simd/is_eqz.hpp(17),
>                  from ./include/boost/simd/function/is_eqz.hpp(46),
>                  from ./include/boost/simd/arch/common/simd/function/logical_not.hpp(12),
>                  from ./include/boost/simd/function/simd/logical_not.hpp(13),
>                  from ./include/boost/simd/function/logical_not.hpp(42),
>                  from ./include/boost/simd/arch/x86/sse2/simd/function/is_greater_equal.hpp(15),
>                  from ./include/boost/simd/function/simd/is_greater_equal.hpp(19),
>                  from ./include/boost/simd/function/is_greater_equal.hpp(49),
>                  from ./include/boost/simd/arch/common/simd/function/is_gez.hpp(15),
>                  from ./include/boost/simd/function/simd/is_gez.hpp(13),
>                  from ./include/boost/simd/function/is_gez.hpp(45),
>                  from ./include/boost/simd/arch/common/simd/function/plus.hpp(12),
>                  from ./include/boost/simd/function/simd/plus.hpp(13),
>                  from ./include/boost/simd/function/plus.hpp(51),
>                  from ./include/boost/simd/arch/common/simd/function/abs.hpp(18),
>                  from ./include/boost/simd/function/simd/abs.hpp(13),
>                  from ./include/boost/simd/function/abs.hpp(62),
>                  from ./include/boost/simd/arch/common/simd/function/is_inf.hpp(15),
>                  from ./include/boost/simd/function/simd/is_inf.hpp(13),
>                  from ./include/boost/simd/function/is_inf.hpp(45),
>                  from ./include/boost/simd/arch/common/generic/function/saturate.hpp(14),
>                  from ./include/boost/simd/function/scalar/saturate.hpp(14),
>                  from ./include/boost/simd/function/saturate.hpp(65),
>                  from ./include/boost/simd/arch/common/scalar/function/minus_s.hpp(17),
>                  from ./include/boost/simd/arch/common/scalar/function/minus.hpp(47),
>                  from ./include/boost/simd/function/scalar/minus.hpp(14),
>                  from ./include/boost/simd/function/minus.hpp(50),
>                  from ./include/boost/simd/arch/common/simd/function/unary_minus.hpp(20),
>                  from ./include/boost/simd/function/simd/unary_minus.hpp(13),
>                  from ./include/boost/simd/function/unary_minus.hpp(61),
>                  from ./include/boost/simd/arch/common/scalar/function/genmask.hpp(14),
>                  from ./include/boost/simd/function/scalar/genmask.hpp(15),
>                  from ./include/boost/simd/function/genmask.hpp(51),
>                  from ./include/boost/simd/arch/common/simd/function/make.hpp(16),
>                  from ./include/boost/simd/function/simd/make.hpp(13),
>                  from ./include/boost/simd/function/make.hpp(59),
>                  from ./include/boost/simd/arch/common/simd/function/combine.hpp(12),
>                  from ./include/boost/simd/function/simd/combine.hpp(15),
>                  from ./include/boost/simd/function/combine.hpp(54),
>                  from ./include/boost/simd/arch/common/generic/function/autofold.hpp(12),
>                  from ./include/boost/simd/arch/common/generic/function/autodispatcher.hpp(14),
>                  from ./include/boost/simd/function/simd/repeat_lower_half.hpp(14),
>                  from ./include/boost/simd/function/repeat_lower_half.hpp(49),
>                  from ./include/boost/simd/arch/common/simd/function/shuffle/repeat.hpp(12),
>                  from truc.cpp(1):
> ./include/boost/simd/arch/x86/sse1/simd/function/topology.hpp(137): error: not a class or struct name
>           , repeat_shuffle
> 

Obviously, there is a way to make the message go away by adding an include before, but it seems to go against the guideline:
_ll files must explicitly include and/or depend on the components that they use, regardless of whether they may already depend on it implicitly in certain situations._

FWIW, I stumbled on the issue while tracking a truncation issue signaled by intel15 when instantiating **boost::simd::detail::is_repeat<-3, 0, -2, -1>**

**Comment by jfalcou** [comment]
The thing is it's a detail component meant to be included internally, so this state of affair doesn't surprise me.

**Comment by aminiussi** [comment]
Yet, is it worth trying to fix it ? (not sure how, but the hierarchy_pattern and repeat_shuffle struct seems independent and could be put in separate headers, thus minimizing the included file ?)

**Comment by jfalcou** [comment]
Maybe but for me it's low-prio. People aren't supposed to use that int he public API.

**Comment by aminiussi** [comment]
Ok, I got rid of the warning in the meantime (PR #430)

**Comment by jfalcou** [comment]
Let's close this one shall we ?
