### ISSUE TITLE
`boost::simd::next_power_of_2` for sized integer types

### ISSUE THREAD

**Issue by timblechmann** [agenium-scale/boost.simd#43]
the result of `boost::simd::next_power_of_2( uint_32(1) )` is size_t, but it would be nice if it could be nice if it could be implemented for unsigned integer types as well

**Comment by ghost** [comment]
isn't it what the andre patch on NT2 do ? We can just retrieve it here.

**Comment by timblechmann** [comment]
:)

it is ... apparently andre and me came across the same warning ... sry for the noise
