### ISSUE TITLE
reorganize `sdk` directory

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#44]

**Comment by jfalcou** [comment]
this include : 
- move all as_\* and *_of outside
- make a using for as__/__of coming from dispactch

**Comment by jfalcou** [comment]
I tired movign everythign outside and the main folder becomes cluttered :/
I think SDK is too kitchen sink but most meta-unctions cna live in simd/meta and other non-meta stuff can be moved to main folder OR detail if needed.

**Comment by ccharly** [comment]
yup I agree. My main problem was actuay the name. Moving most of the stuff one level upper would be ok. And yes moving all meta functions into a proper meta directory is good
