### ISSUE TITLE
Can Boost.SIMD find the delimeters in an HTTP header

### ISSUE THREAD

**Issue by vinniefalco** [agenium-scale/boost.simd#445]
I'd like to know if its practical to port this function to Boost.SIMD:
https://github.com/h2o/picohttpparser/blob/master/picohttpparser.c#L107

**Comment by jfalcou** [comment]
We dont wrap _mm_cmpestri in itself has it's probably hardto 1/ find a proper higher level semantic as string in themselves are not somethign we support 2/ implement it in emulation mode. 

What I would do is to see if the use of _mm_cmpestri can't be repalced by an actual SIMD-ified std::find_if, something which is on our lsit of things to do.

**Comment by jfalcou** [comment]
We can continue discussing this on the Google Groups if you want :  https://groups.google.com/forum/#!forum/boost-simd

**Comment by kreuzerkrieg** [comment]
Any news regarding `find`? As I see from the code, boost::simd::find uses std::find and works on `segmented_aligned_range`. Should we see any performance boost?

**Comment by jfalcou** [comment]
the `segmented_range` is made so the middle part of it will be vectorized. What we do is that we try to find a vector that has any value fitting the find criterion. If we foudn one, we restrict the find to the small amount of value the register holds. So there shoukd be a speedup yes.

**Comment by kreuzerkrieg** [comment]
Actually I saw speedup, ~2x, but didnt get why it works :) Thank for the explanation.
Stumbled upon this [link](http://0x80.pl/articles/simd-strfind.html) it will be interesting to check which implementation is faster when dealing with strings
