### ISSUE TITLE
Link to algorithm tutorial broken

### ISSUE THREAD

**Issue by gnzlbg** [agenium-scale/boost.simd#447]
In [this page](https://developer.numscale.com/boost.simd/documentation/develop/tutorial-simd-loop.html) there is a link to the Algorithm tutorial that seems broken.

**Comment by jfalcou** [comment]
Which link actually ?

**Comment by viboes** [comment]
Please, fix the links.
Not Found

The requested URL /boost.simd/documentation/develop was not found on this server.
Apache/2.4.10 (Debian) Server at developer.numscale.com Port 443

**Comment by viboes** [comment]
https://developer.numscale.com/boost.simd/documentation/develop

In https://github.com/NumScale/boost.simd#important-links-

Important Links :

    The current Issues List
    [The documentation](https://developer.numscale.com/boost.simd/documentation/develop)



and at the end of the same page

Now, you can [have a look at our documentation](https://developer.numscale.com/boost.simd/documentation/develop
) to follow one of our tutorials on how to use Boost.SIMD.

**Comment by ccharly** [comment]
Hi, we're about to release the new version of `boost.simd` (which will also be renamed during the process). The future documentation will then be adapted to this new version.

The current version of the documentation has been disabled for now. We're sorry for that. I'll keep you in touch.

Thanks.
