### ISSUE TITLE
Documentation unclear on the dupplication of scalar and SIMD code

### ISSUE THREAD

**Issue by gnzlbg** [agenium-scale/boost.simd#448]
The documentation mentions in the introduction that one can use C++14 lambdas with SIMD algorithms. 

However, most of the examples show that one needs to duplicate the SIMD kernels, with one version for packs and one version for scalars.

I would however have expected that if I am using a C++14 lambda [0]  I would only need to write my algorithm once, for packs. I would expect that there is an iteration function/algorithm/... that automatically instantiates my code for multiple pack sizes: max pack size, max pack size / 2, ..., until pack size == 1. That way I would just need to write the algorithm once. [1]

From the tone in the docs and the STL algorithms I guess that there is already functionality in the library for doing this. I just have a hard time finding it. I think the docs should always use this functionality if it is present, and delay the presentation of how the raw loops are written to a more advanced section that says: this is how the iterate algorithm is implemented, and this is how you can implement your own raw loops if you need too. But remember that optimal performance is tricky.

[0] or a template function/struct with templated operator().
[1] The examples that just use two pack sizes (N, and 1), are probably are sub-optimal. Consider looping over 96 element with a max pack size of 8. One wants to use a pack size of 8 first, and a pack size of 4 afterwards (instead of 8 and 1).

**Comment by jfalcou** [comment]
I think you're right on the tutorial order, we'll see to fix that

**Comment by gnzlbg** [comment]
This one:

> A more elegant way of achieving this is demonstrated in the tutorial [Algorithm](https://developer.numscale.com/boost.simd/documentation/develop/md__home_charly_w_workspace_cpp_developer-numscale-com__git_boost.simd_develop_doc_custom_sections_tutorials_tutorial_algorithm.html#tutorial-algorithm).

**Comment by jfalcou** [comment]
OK found it
