### ISSUE TITLE
Can't find the documentation on concepts

### ISSUE THREAD

**Issue by gnzlbg** [agenium-scale/boost.simd#449]
The algorithm section of the reference documentation (there doesn't seem to be any other documentation about those) does not document any of the concepts used (or at least I cannot find this documentation). 

For example, some algorithms take a `BinOp` parameter. What is `BinOp`? 

It is obvious to me that it must be a binary operator. What is not obvious is what requirements should it fulfill. For example:

- Can my binary operator have hard-coded scalar types? `BinOp::operator()(double const&, double const&)` ?
- Can my binary operator have hard-coded pack types? 
- Should my binary operator be templated? If so:
  - Should the templated code be valid for both scalars and packs? only scalars? only packs?

I was interested in particular in the last two questions. Can I assume that I can use all pack operations inside my binary operator? (If so, this means that for handing the remainders the algorithms must pass something like a pack of size one). 

Independently of how it actually works, I think it is useful to teach this somewhere in the documentation.

**Comment by jfalcou** [comment]
We need to link the basic concepts to the cppreference pages desscribing them.

For the requirements, the binary operators we await must be valid for both scalars and packs as they're used for both the pack and scalar part of the algorithms. This means template operator() using boost.sidm operators/functions that all work on both OR polymorphic lambda.

We'll add that to the doc.

**Comment by gnzlbg** [comment]
There is a link in the reference to [Concepts](https://developer.numscale.com/boost.simd/documentation/develop/group__group-concept.html) but that page is empty, I guess that's what you mean?

> For the requirements, the binary operators we await must be valid for both scalars and packs as they're used for both the pack and scalar part of the algorithms. This means template operator() using boost.sidm operators/functions that all work on both OR polymorphic lambda.

Does this mean that if I want to use some pack specific functionality in my kernels, I need to duplicate my code?

**Comment by jfalcou** [comment]
The concepts page is indeed empty, need to be fixed.

For your other question,do you have such an example so I can fully see what you want to do ?

**Comment by gnzlbg** [comment]
> For your other question, do you have such an example so I can fully see what you want to do 

I just wanted to branch inside my C++14 lambda binary kernel depending on the values. Should I use an if? or somehting like `bs::if_zero_else_one(bs::is_less(...));` ?

I would expect that inside kernels I need to use SIMD branches, and that scalars are just handled via `pack<T, 1>` so that everything still works.

**Comment by jfalcou** [comment]
I would go and use the `if_*` functions that do the obvious thing in scalar. Note that scalar parts of algorithms processign are done using the scalar value directly, not `pack<T,1>` as all functions are anyway provided for true scalar types.

**Comment by gnzlbg** [comment]
> I would go and use the if_* functions that do the obvious thing in scalar. Note that scalar parts of algorithms processign are done using the scalar value directly, not pack<T,1> as all functions are anyway provided for true scalar types

Cool, thanks! I missed this fact in the docs I guess :/

**Comment by jfalcou** [comment]
[Branching tutorial is here](https://developer.numscale.com/boost.simd/documentation/develop/tutorial-branching.html)

**Comment by jfalcou** [comment]
I think we may ask that `BinOp` models some kind of PolymorphicCallable to enforce the fact it needs to be template. Not sure somethign like this exists in std or if we should make one.

**Comment by gnzlbg** [comment]
An alternative that might also work, would be to say that packs and scalars model some `SIMDPack`  concept (of which scalars are just like simd packs of length 1), that provides a set of SIMD operations. The operators, predicates, etc... can be required to accept any type that models `SIMDPack`, which means that they should be generic/polymorphic. This also makes it clear which operations are valid on the arguments.

(`SIMDPack` is just a strawman name, i am pretty sure a better name for this exist.)

**Comment by jfalcou** [comment]
I see, this make sense. If you look at some of our function doc, we already refere to things like `Value`, `IEEEValue` etc, where `Value` means scalar or pack. So maybe it's roughly this.

**Comment by jfalcou** [comment]
This SIMDPack concept write itself : must supports cardinal_of, value_of and be a RegularType. I think this is the right way

**Comment by jfalcou** [comment]
@gnzlbg I pushed a issue_449-concept_doc branch. It currently only contains Concept spec for the basic Value types but would like your opinions on those before I dig intot he other one.

**Comment by gnzlbg** [comment]
@jfalcou did you push that commit yet? Or which commit does contain the changes?

**Comment by jfalcou** [comment]
sorry, it is now

**Comment by jfalcou** [comment]
Feel free to directly comment in the commit

**Comment by jfalcou** [comment]
Your comments has been integrated. If everythign is OK, I jump to the concepts neede for the algorithms

**Comment by jfalcou** [comment]
@gnzlbg @CaseyCarter, next commit implements your comments

**Comment by jfalcou** [comment]
Task left:
 - [x] Value et al concept
 - [ ] Callable used in algorithms
