### ISSUE TITLE
scalar copysign has bad performance on msvc

### ISSUE THREAD

**Issue by timblechmann** [agenium-scale/boost.simd#457]
`std::copysign`/`copysignf` isn't inlined in msvc, so it is an order of magnitude slower than `boost::math::copysign`. maybe worth to change the default?

**Comment by jfalcou** [comment]
Is the 

    return bitwise_or(bitofsign(a1), bitwise_notand(Signmask<A0>(), a0));

version better all the time then ?

The calls to the standard facilities was seen as a good scenario "long time ago", we can just use our implementation all the time if needed or does it only affects MSVC ?

**Comment by timblechmann** [comment]
i've only done benchmarks for `std` vs `boost::math`. boost.math should be equivalent to the bit wise handling, so that's probably fine as well

**Comment by jfalcou** [comment]
Care to test the issue_457-scalar_copysign branch  ?
