### ISSUE TITLE
cmake dependency

### ISSUE THREAD

**Issue by aminiussi** [agenium-scale/boost.simd#463]
Hi,
Guess you already saw it, but still:

> CMake Warning (dev) at CMakeLists.txt:69 (add_dependencies):
>   Policy CMP0046 is not set: Error on non-existent dependency in
>   add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
>   Use the cmake_policy command to set the policy and suppress this warning.
> 
>   The dependency target "update.boost-header-only" of target "update.check"
>   does not exist.
>

**Comment by jfalcou** [comment]
which CMake version is it ?

**Comment by aminiussi** [comment]
> [alainm@gurney
>  intel15]$ cmake --version
> cmake version 3.1.0-rc1
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> [alainm@gurney intel15]$ 
>

**Comment by aminiussi** [comment]
The default one had an issue with FindBoost.cmake

```
[alainm@gurney intel15]$ /usr/bin/cmake -version 
cmake version 2.8.12.2
[alainm@gurney intel15]$ 

```

**Comment by jfalcou** [comment]
This means we may need to up the base version of CMake in the project. @ccharly  thoughts ?

**Comment by aminiussi** [comment]
Note that, for some reason, I had to set **CMAKE_CXX_COMPILER** variable to get the _icpc_ compiler selected (by the way, the selected compiler is not printed by default if I am not mistaken, which can be stressful):

> /usr/bin/cmake -DBOOST_ROOT=/softs/exp/boost_1.63 -DCMAKE_CXX_COMPILER=icpc  -DDEV=1 ..

That triggered a re-run of cmake which selected the platform FindBOOST.cmake (I think you provide your own ?)  which fail to take BOOST_ROOT into account.
I guess.

> -- ## -----------------------------------------------------------------------------
> 
>    ns.cmake is now installed!
>    ns.cmake's (init) targets have been excluded from the `all` target!
> 
> -- ## -----------------------------------------------------------------------------
> -- Boost version: 1.63.0
> -- [Boost.SIMD]: ## Adding external project: STF
> -- [Boost.SIMD]: ## Adding external project: NS_BENCH
> -- [Boost.SIMD]: Compilation flags:  -std=c++11 -Wall -Wshadow -Wextra
> -- [Boost.SIMD]: Global flags:  -std=c++11 -Wall -Wshadow -Wextra -fp-model precise
> -- [Boost.SIMD]: Testing flags:  -O2
> -- [Boost.SIMD]: Benchmark flags: 
> -- [Boost.SIMD]: Compiler does not support gcov. coverage targets disabled
> -- ## -----------------------------------------------------------------------------
> --    Unit and performances tests are available.
> --    Please run the update targets to install pre-requisites:
> --        make -j1 update / ninja -j1 update
> -- ## -----------------------------------------------------------------------------
> -- Configuring done
> You have changed variables that require your cache to be deleted.
> Configure will be re-run and you may have to reset some variables.
> The following variables have changed:
> CMAKE_CXX_COMPILER= icpc
> 
> -- The C compiler identification is Intel 15.0.0.20150121
> -- The CXX compiler identification is Intel 15.0.0.20150121
> -- Check for working C compiler: /softs/intel/composer_xe_2015.2.164/bin/intel64/icc
> -- Check for working C compiler: /softs/intel/composer_xe_2015.2.164/bin/intel64/icc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /softs/intel/composer_xe_2015.2.164/bin/intel64/icpc
> -- Check for working CXX compiler: /softs/intel/composer_xe_2015.2.164/bin/intel64/icpc -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Found Git: /softs/exp/git-master/bin/git (found version "2.2.0.rc2.12.ge69b1ce") 
> -- ## -----------------------------------------------------------------------------
> 
>    ns.cmake is now installed!
>    ns.cmake's (init) targets have been excluded from the `all` target!
> 
> -- ## -----------------------------------------------------------------------------
> CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1138 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.41.0
> 
>   Boost include path: /usr/include
> 
>   Detected version of Boost is too old.  Requested version was 1.60 (or
>   newer).
> Call Stack (most recent call first):
>   cmake/ns/ns.cmake:140 (find_package)
>   CMakeLists.txt:42 (NS_find_package)
> 
> 
> CMake Error at cmake/ns/ns.cmake:70 (message):
>   [Boost.SIMD]: 'Boost' package is required but has not been found!
> Call Stack (most recent call first):
>   cmake/ns/ns.cmake:85 (NS_message)
>   cmake/ns/ns.cmake:143 (NS_error)
>   CMakeLists.txt:42 (NS_find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/scratch/alainm/view/boost.simd/intel15/CMakeFiles/CMakeOutput.log".
> [alainm@gurney intel15]$

**Comment by jfalcou** [comment]
? Specifying the compiler there is what I always do so I am a bit lost there. As or displayign the compiler, could be good yes.

And for FindBoost, no we provide a FindBoostSIMD, which is different. We use the out of the box FindBoost.

**Comment by jfalcou** [comment]
actually we use find_package for finding boost.

**Comment by aminiussi** [comment]
I think find_package ends up calling Find<PackageName>.cmake

**Comment by ccharly** [comment]
The first problem concerning the `update.boost-header-only` might be because we didn't check for `if (USE_SELF_BOOST)` before actually adding the dependency. At this point, if `-DUSE_SELF_BOOST=` is not provided, then `update.boost-header-only` should not be created.

https://github.com/NumScale/boost.simd/blob/develop/CMakeLists.txt#L69

**Comment by ccharly** [comment]
I don't really know what to say about cmake not printing the default detected compilers, 'cause in your example (after re-running cmake if I'm not mistaken) I can clearly see the compiler:

```
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= icpc

-- The C compiler identification is Intel 15.0.0.20150121
-- The CXX compiler identification is Intel 15.0.0.20150121
```

Maybe I've missed something here?

**Comment by aminiussi** [comment]
No you're right, I was just expecting to see icpc or g++ or whatever value set in **CMAKE_CXX_COMPILER** as I'm used to, although that could be with AutoTool. 
Sorry for that one.

**Comment by aminiussi** [comment]
Value which I can see, too....

**Comment by ccharly** [comment]
No that's ok :) We can still add some more "verbose" information like this one.

**Comment by jfalcou** [comment]
so actions ? 

- [x] add the if() around the target addition
- [x] print CMAKE_CXX_COMPILER 

?

**Comment by ccharly** [comment]
I'd say both. The first one is obviously an error on our side and this needs to be fixed. The second one might a good "bonus". :)

**Comment by ccharly** [comment]
I can do that later today or tomorrow.

**Comment by jfalcou** [comment]
@aminiussi  care to check with branch issue_463-cmake-deps ?

**Comment by aminiussi** [comment]
I'm giving it a try.
I'm having some gpfs issue so right now the cmake is stalled.
I'll let you know when it's back

**Comment by aminiussi** [comment]
Looks ok on that branch.

**Comment by aminiussi** [comment]
Maybe unrelated, and I probably had that issue before, but the make does not seems to take my build type into account:

> alainm@gurney intel15]$ grep CMAKE_BUILD_TYPE CMakeCache.txt
> CMAKE_BUILD_TYPE:STRING=Release
> [alainm@gurney intel15]$

But I see no optimization option nor -DNDEBUG during the build,
just _-std=c++11 -Wall -Wshadow -Wextra -fp-model precise_

> [alainm@gurney intel15]$ make unit VERBOSE=1
> ...
> [  0%] Building CXX object test/api/algorithm/CMakeFiles/api.algorithm.transform.unit.dir/transform.cpp.o
> cd /scratch/alainm/view/boost.simd/intel15/test/api/algorithm && /softs/intel/composer_xe_2015.2.164/bin/intel64/icpc    -std=c++11 -Wall -Wshadow -Wextra -fp-model precise -I/scratch/alainm/view/boost.simd/include -I/scratch/alainm/view/boost.simd/test -I/scratch/alainm/view/boost.simd/bench -I/scratch/alainm/view/boost.simd/exhaustive -I/scratch/alainm/view/boost.simd/intel15/_install/include -I/softs/exp/boost_1.63/include    -o CMakeFiles/api.algorithm.transform.unit.dir/transform.cpp.o -c /scratch/alainm/view/boost.simd/test/api/algorithm/transform.cpp
>

**Comment by jfalcou** [comment]
We froce the unit test to be setup as Debug always. See the root CMakelists in unit/

**Comment by aminiussi** [comment]
I'm not sure how the:

> set(CMAKE_BUILD_TYPE "Debug")

works in test/CMakeLists.txt, but I do not see any debug option in the build log. 
Could be due ti the fact I'm building each target individually.
Oh well...

**Comment by jfalcou** [comment]
it shodlu be working even with individual targtes
