### ISSUE TITLE
doc.bitwise.ilog2.unit asserting

### ISSUE THREAD

**Issue by aminiussi** [agenium-scale/boost.simd#477]
Hi, 
**doc.bitwise.ilog2.unit** fails with the following assertion:

> doc.bitwise.ilog2.unit: /home/alainm/views/boost.simd/include/boost/simd/arch/common/simd/function/ilog2.hpp:40: boost::simd::ext::impl_ilog2_<boost::simd::detail::is_native<X>, boost::dispatch::cpu_, boost::simd::pack_<boost::dispatch::floating_<T>, X> >::result boost::simd::ext::impl_ilog2_<boost::simd::detail::is_native<X>, boost::dispatch::cpu_, boost::simd::pack_<boost::dispatch::floating_<T>, X> >::operator()(const A0&) const [with A0 = boost::simd::pack<float, 4ul>; X = boost::simd::sse_; boost::simd::ext::impl_ilog2_<boost::simd::detail::is_native<X>, boost::dispatch::cpu_, boost::simd::pack_<boost::dispatch::floating_<T>, X> >::resul t = boost::simd::pack<int, 4ul, boost::simd::sse_>]: Assertion `(assert_all(a0 > 0))&&("Logarithm is not defined for zero or negative values.")' failed.
> 
on linux with 

> $ g++ --version
> g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Is it specific to that environment ?

**Comment by jfalcou** [comment]
the test is maybe wrong but that's strange. @jtlap can you check ?

**Comment by jtlap** [comment]
It's not a real problem, it's a feature! there was the computation of ilog2(-1) in the doc example.
I have made a correction. Perhaps it is not worth a PR.

Tell me if I push that directly on develop

**Comment by jtlap** [comment]
without answer I just pushed the micro change

**Comment by jfalcou** [comment]
Fixed in a8dcdfbc5466f188388263a3b543369f949d5bde
