### ISSUE TITLE
Using masked load/store

### ISSUE THREAD

**Issue by bmmogensen** [agenium-scale/boost.simd#478]
Hi NumScale. 

Thanks for the excellent work you've done with boost.simd - I've found the library very useful and easy to use. However, I currently find myself in deeper water, as I'm looking to use a mask to filter which floating point values to load from a given memory location. It seems that such operation is supported, as the library uses the intrinsics __mm*_maskload_* in function\load.hpp, but I cannot find an example on how to actually do this.

Could you point me in the right direction?

Best regards,
Bjorn

**Comment by jtlap** [comment]
Have you have a look to the simd tests files of load ?

**Comment by bmmogensen** [comment]
Thanks a lot - that was the hint I needed, but couldn't find in the documentation. I used the file boost.simd\test\function\simd\load\mask.arithmetic.cpp to make the following example on how to load only a part of the values in the array and then use bs::sum to calculate the sum of the loaded value to validate that the mask was applied correctly.

    #include <array>
    #include <iostream>
    #include <boost/simd.hpp>
    #include <boost/simd/mask.hpp>
    #include <boost/simd/function/load.hpp>
    #include <boost/simd/function/sum.hpp>
    
    namespace bs = boost::simd;
    
    int main()
    {
      std::array<double,4> datasrc = {{1.0,2.0,3.0,4.0}};
      std::array<bs::logical<double>, 4> masksrc = { { true, true, true, true } };
      using value_type = bs::pack<double, 4>;
      using mask_type = bs::as_logical_t<value_type>;
      for (auto it = masksrc.rbegin();it!=masksrc.rend();it++)
      {
        mask_type mask = bs::load<mask_type>(masksrc.data());//load mask
        value_type value = bs::load<value_type>(bs::mask(datasrc.data(), mask));//load data with mask
        *it = false;//do not load the value in in the next calculation
        std::cout << "result of bs::sum: " << bs::sum(value) << std::endl;
      }
      return 0;
    }

The output is as expected:
result of bs::sum: 10
result of bs::sum: 6
result of bs::sum: 3
result of bs::sum: 1

**Comment by jfalcou** [comment]
A simple note: the interface is not yet documented as it may shift as the support of masking is still in flux.
So expect changes there.

**Comment by jfalcou** [comment]
Sidenote : I'll probably reuse your example for the doc of this ^^

**Comment by bmmogensen** [comment]
No problem, I'll be sure to look out for changes. 

On a side note, I noticed a problem with aligned_store using masked pointers, which I reported here: https://github.com/NumScale/boost.simd/issues/481
