### ISSUE TITLE
doc.range.transform_reduce2b.unit build is failing on common recent ubuntu and boost

### ISSUE THREAD

**Issue by aminiussi** [agenium-scale/boost.simd#492]
The build of unit test is failing with a quite commun distrib/compiler.

>alainm@jarvis$ more /etc/debian_version 
>stretch/sid
>alainm@jarvis$ uname -a
>Linux jarvis 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
>alainm@jarvis$ g++ --version
>g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
>Copyright (C) 2015 Free Software Foundation, Inc.
>This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>alainm@jarvis:$ 

The log and cmake cache files are attached:

[make.txt](https://github.com/NumScale/boost.simd/files/883746/make.txt)
[CMakeCache.txt](https://github.com/NumScale/boost.simd/files/883196/CMakeCache.txt)

Thx

**Comment by jfalcou** [comment]
The log is not very informative as I see no compierl error in it

**Comment by aminiussi** [comment]
Yeah, since **tee** does not redirect stderr....
I updated the [make.txt](https://github.com/NumScale/boost.simd/files/883746/make.txt) file.

**Comment by jfalcou** [comment]
are you up to date with HEAD on dev ? i fixed somethign similar recently

**Comment by jfalcou** [comment]
OK bug reproduced and beign fixed

**Comment by jfalcou** [comment]
9e9d9ba shoudl fix this
