### ISSUE TITLE
Precision issue with trigo functions

### ISSUE THREAD

**Issue by serge-sans-paille** [agenium-scale/boost.simd#497]
This may looks like a corner case, but

```
#include <boost/simd/function/cos.hpp>
#include <cmath>
#include <iostream>
int main() {
  double d = 1.0339418859915777;
  std::cout << (boost::simd::cos(d) - std::cos(d)) << "\n";
  return 0;
}
```

returns

```
> 1.11022e-16
```

One one simulation code of a pythran client, this leads to a regression.

**Comment by jfalcou** [comment]
Considering that the DBL_EPSILON = 2.220446e-16, we're actually within 0.5 ULP
Was it at 0 ULP before ?

**Comment by serge-sans-paille** [comment]
yes :-/ not the release -1, but probably release -2 or -3

**Comment by jfalcou** [comment]
0.5 ULP is actually what's the standard mandate. So all in all, we're correct. :/ Not sure what to do then

**Comment by jfalcou** [comment]
are you doing some thign like comparing double with == ? That's the real issue IMHO

**Comment by jtlap** [comment]
I think we can do nothing in this case. It is not even sure that our result is not more accurate than std one. Also the result can depend of the the compiler version and the flag it uses. 0.5 ulp: we can get no more...

**Comment by serge-sans-paille** [comment]
I double checked the customer code, he's got a data race which was the real culprit.

To apologize for the noise, here is some good news:

    https://github.com/serge-sans-paille/pythran/pull/658

**Comment by jfalcou** [comment]
Good :) 

and GOOD :)
