### ISSUE TITLE
Better SIMD sort

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#5]
There is only an implementation for SSE right now.

[original issue here](https://github.com/jfalcou/nt2/issues/540).

**Comment by jfalcou** [comment]
Radical question : do we need sorting on a single pack ? 
I think we can just get rid of it.

**Comment by ccharly** [comment]
We can probably ignores it for now and wait for a valid use case? I mean, if someone does need it, then we will think about it.

**Comment by jfalcou** [comment]
Closing for now
