### ISSUE TITLE
Fix interactions between floating points and unsigned integers 

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#506]
Functions like `rshr`, `rshl`, `ldexp` and maybe some others, can accept `boost::dispatch::integer_` as the second parameters. However, the code inside makes the assumption that the second parameter is actually a signed integer.

Two solutions:
- Restrict the dispatching to `ints_`
- Fix the code so that both types are actually valid

**Comment by jtlap** [comment]
I found one spot with invalid conversion in pedantic ldexp. I'll push a branch with augmented tests and this correction.
