### ISSUE TITLE
deinterleaving performance

### ISSUE THREAD

**Issue by kreuzerkrieg** [agenium-scale/boost.simd#515]
Tried to deinteleave data using Boost.SIMD. However the performance is worse (~25% slower) than just running in for loop over the input and filling the two result vectors. 
The code
```
void foo(Buffer& input, Buffer& U, Buffer& V)
{
    using pack_t = bs::pack<uint8_t>;
    const size_t buffSize = input.size() / 2;
    U.resize(buffSize);
    V.resize(buffSize);

    auto end = input.size() / pack_t::static_size / 2;
    for(auto i = 0u; i < end; ++i)
    {
        pack_t v0 = bs::aligned_load<pack_t>(input.data() + i * 2 * pack_t::static_size);
        pack_t v1 = bs::aligned_load<pack_t>(input.data() + (i * 2 + 1) * pack_t::static_size);
        auto res = bs::deinterleave(v0, v1);
        bs::aligned_store(res[0], U.data() + i * pack_t::static_size);
        bs::aligned_store(res[1], V.data() + i * pack_t::static_size);
    }
}

```
the Buffer is defined as `std::vector<uint8_t>`. Am I doing something wrong? Yes, I checked the FAQ, Release, x64, VS2015 Update 3

compiler command line

> /GS /Qpar /GL /W3 /Gy /Zc:wchar_t /Zi /Gm- /O2 /sdl  /Zc:inline /fp:precise /D "NDEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /arch:AVX2 /Gd /Oi /MD /EHsc /nologo

**Comment by jfalcou** [comment]
Looks like a specialisation for deitnerleave is missing on 8 bits integer. We'll get that sorted out quick.

**Comment by jfalcou** [comment]
@kreuzerkrieg care to check if branch  avx2_interleave  is any good for your issue ?

**Comment by kreuzerkrieg** [comment]
you are good to go. performancewise it is as good as my handrolled AVX function. it passed output validation test as well.
And thanks for the prompt fix!
