### ISSUE TITLE
Make Boost.SIMD available on nuget.org

### ISSUE THREAD

**Issue by kreuzerkrieg** [agenium-scale/boost.simd#517]
Please make Boost.SIMD available on nuget.org as native package

**Comment by jfalcou** [comment]
Any links to the procedure ?

**Comment by kreuzerkrieg** [comment]
http://coapp.org/
https://docs.microsoft.com/en-us/nuget/create-packages/native-packages

PugiXml could be an example how to create such a package https://github.com/zeux/pugixml/blob/master/scripts/nuget.autopkg , just drop the lib part.
