### ISSUE TITLE
Recursive packs

### ISSUE THREAD

**Issue by brunom** [agenium-scale/boost.simd#518]
I think that to process 24-bit RGB surfaces, it would be useful to define pack<pack<uint8_t, 3>> but this is doubly disallowed. Packs can't be recursive and the size must be a power of 2. Can you lift these limitations?

**Comment by jfalcou** [comment]
Long answer :D 

- the restriction on pack size being a power of  came from the requirement for any pack to be slicable into 2 packs of exactly half the size. Odd or non-power of 2 size throw this hypothesis to the drain and complexify the implementation of a large number of critical functions

- pack is here to abstract "register" like values. pack of pack make little sense as they're not just container.

The notion of loading pack in multipels and build a aggregate object out of them is a very valid use case though but we think it goes through using standard structure or tuple. #370 is part of this issue and so does all the shuffle and interleave/deinterleave like functions.

Having a `template<typename PixelType> struct RGBS { T r,g,b; };` and appropriate constructor loading/deinterleaving is probably the best way to handle this. As far as simplifyign this goes, we're working on it.
