### ISSUE TITLE
Boost simd infimum slower than no simd one what i'm doing wrong ?

### ISSUE THREAD

**Issue by ThomasRetornaz** [agenium-scale/boost.simd#519]
Hi 

I try to implement a image library using boost simd. I will start with a very simple case ie compute infimum of two vector or store result in a third vector (eg think about erosion based on shifted buffer)

Below a very simplified code of what i try todo 
`
       //create aligned unsigned char vector with random noise
       decltype(auto) ConstructVector(size_t size)
       {
               std::random_device rd;
               std::mt19937 gen(rd());
               std::uniform_int_distribution<> dis(0, 255);

		std::vector<unsigned char, boost::simd::allocator<unsigned char>> m_vect;
               m_vect.reserve(size);
                for (auto i = 0; i < size; ++i) {
                     m_vect.push_back(dis(gen));
              }
               return m_vect;
       }
       
        //define two tags to swicth to the proper operator see below
	struct tag_SIMD_disabled {};
	struct tag_SIMD_enabled {};
       
	template< typename T1, typename T2, typename T3, class tag>
	struct op_Inf;

        //specialized operator no simd aware
	template< typename T1, typename T2, typename T3>
	struct op_Inf<T1, T2, T3, tag_SIMD_disabled>
	{
	public:
		op_Inf() {}
		POUTRE_ALWAYS_INLINE T3 operator()(T1 const &a0, T2 const &a1) POUTRE_NOEXCEPT
		{
			return static_cast<T3>(a0 < a1 ? a0 : a1);
		}
	};
       
       //specialized operator simd aware
	template< typename T>
	struct op_Inf<T, T, T, tag_SIMD_enabled>
	{
	public:
		op_Inf() {}
		template< typename U>
		POUTRE_ALWAYS_INLINE U operator()(U const &a0, U const &a1) POUTRE_NOEXCEPT
		{
                        //std::cout << "U type" << typeid(U).name() <<std::endl; // Display properly U typeclass boost::simd::pack<unsigned char,32,struct boost::simd::avx_>
			return bs::min(a0, a1);
		}
	};
        
        //primary function not simd aware, use pointer facilities
	void PerformInfScalar(const std::vector<unsigned char, boost::simd::allocator<unsigned char>>& vectin1, const std::vector<unsigned char, boost::simd::allocator<unsigned char>>& vectin2, std::vector<unsigned char, boost::simd::allocator<unsigned char>>& vectout)
	{
		//get the specialized operator
		using real_op = typename op_Inf<unsigned char, unsigned char, unsigned char, tag_SIMD_disabled>;
		real_op op;
		//std::cout << "\n" << "call PixelWiseBinaryOpDispatcherWithTag array view template specialization same type,fall back ptr";
		auto i_vinbeg1 = vectin1.data();
		auto i_vinend1 = vectin1.data() + vectin1.size();
		auto i_vinbeg2 = vectin2.data();
		auto i_voutbeg = vectout.data();
		for (; i_vinbeg1 != i_vinend1; ++i_vinbeg1, ++i_vinbeg2, ++i_voutbeg)
		{
			*i_voutbeg = op(*i_vinbeg1, *i_vinbeg2);
		}
	}
        
        //secondary function simd aware, use simd aware operator and boost::simd::transform
	void PerformInfSIMD(const std::vector<unsigned char, boost::simd::allocator<unsigned char>>& vectin1, const std::vector<unsigned char, boost::simd::allocator<unsigned char>>& vectin2, std::vector<unsigned char, boost::simd::allocator<unsigned char>>& vectout)
	{
		//get the specialized operator
		using real_op = typename op_Inf<unsigned char, unsigned char, unsigned char, tag_SIMD_enabled>;
		real_op op;
		//std::cout << "\n" << "call PixelWiseBinaryOpDispatcherWithTag array view template specialization same type,fall back ptr SIMD";
		auto i_vinbeg1 = vectin1.data();
		auto i_vinend1 = vectin1.data() + vectin1.size();
		auto i_vinbeg2 = vectin2.data();
		auto i_voutbeg = vectout.data();
		bs::transform(i_vinbeg1, i_vinend1, i_vinbeg2, i_voutbeg, op);
	}
    }
`
I use visual 2017 compiler and i have enable AVX instuctions
Eg : Advanced Vector Extensions (/arch:AVX)  and flag __SSE2__,__SSE3__,__SSSE3__,__SSE4_1__,__SSE4_2__,__AVX__,__SSE2AVX__
and use 
GIT_TAG 3695ff6babc63deab068ccc0776825478dac27cb

When in benchmark function
`
    BOOST_AUTO_TEST_CASE(operatorinfdispatch)
    {
	const auto size = 1000 * 1000;
	const auto inputVect1 = ConstructVector(size);
	const auto inputVect2 = ConstructVector(size);
	std::vector<unsigned char, boost::simd::allocator<unsigned char>> ouputVect(size);

	auto iteration = 10000;
	std::cout << "********************************" << std::endl;
	{
		poutre::Timer timer;
		std::cout << "********************************" << std::endl;
		timer.Start();
		for (auto i = 0; i < iteration; ++i)
			PerformInfSIMD(inputVect1, inputVect2, ouputVect);
		timer.Stop();
		std::cout << "Time testInf simd" << timer << std::endl;
		timer.Reset();
		std::cout << "********************************" << std::endl;
	}

	{
		std::cout << "********************************" << std::endl;
		poutre::Timer timer;
		timer.Start();
		for (auto i = 0; i < iteration; ++i)
			PerformInfScalar(inputVect1, inputVect2, ouputVect);
		timer.Stop();
		std::cout << "Time testInf scalar " << timer << std::endl;
		timer.Reset();
		std::cout << "********************************" << std::endl;
	}
    }
`

SIMD aware version is 16 times slower than no simd one (The opposite of what is expected at least)
Eg First case take 17s and second one take 845 ms

- I obviously checked three or more times that i measuring the right function
- all seems be properly aligned and in check that if pass through bs::transform  in PerformInfSIMD
- I check that when i pass through  PerformInfSIMD, i use  bs::transform and type U will be
boost::simd::pack<unsigned char,32,struct boost::simd::avx_> during simd aware loop in  bs::transform
 

May i make something stupid but i don't know where
If you could take some times on this issue
Regards

**Comment by jfalcou** [comment]
I'm gonna give this a round this afternoon but meanwhile :
 
 - are you compiling in Release and 64 bits ?
 - you may want to add \DNDEBUG if it is not set
 - you may want to specify \DBOOSt_SIMD_ASSUME_SSE4_2 so emulated aVX functiosn use proper level of SSE.

AVX has no integers supprot so we should gracefully slice the register of 32 chars and calls the SSE version twice. Do you have an appropriate speedup in SSE mode ?

**Comment by ThomasRetornaz** [comment]
Thanks for your quick feedback

- I compile in release and 64 bits

- NDEBUG is set 

see below my complete list of flags
`
WIN32
_WINDOWS
NDEBUG
_SCL_SECURE_NO_WARNINGS
_SECURE_SCL=0
_HAS_ITERATOR_DEBUGGING=0
__SSE2__
__SSE3__
__SSSE3__
__SSE4_1__
__SSE4_2__
__AVX__
__SSE2AVX__
_CRT_SECURE_NO_DEPRECATE
_CRT_NONSTDC_NO_DEPRECATE
_WIN64
BOOST_ALL_NO_LIB
POUTRE_DYNAMIC
BOOST_TEST_DYN_LINK
CMAKE_INTDIR="Release"
`

- if i add BOOST_SIMD_ASSUME_SSE4_2 obviously its generate a warning that __SSE4_2__
is already declared

- I use OptimizeForArchitecture.cmake for detecting the architecture and set the proper flags may better approach exist

- I regenerate my solution with sse2 enable only.
- Execution times beetween simd and no simd versions is almost equal
- I check that when i pass through PerformInfSIMD, i use bs::transform and type U will be
U typeclass boost::simd::pack<unsigned char,16,struct boost::simd::sse_> during simd aware loop in bs::transform     

Regards

**Comment by jfalcou** [comment]
Bug reproduced and it happens that a function is not properly emulated. Fix incoming.
Can you check performances using AVX2 ?

**Comment by ThomasRetornaz** [comment]
Thanks for your feedback
Unfortunately i can't check performances using AVX2 
Just for my information which function is not properly emulated (or i can wait for the fix and inspect the diff)
Regards TR

**Comment by jfalcou** [comment]
OK. as for which function, I'm still in the guts of the thing ;)

**Comment by jfalcou** [comment]
Turns out priority issues between the "emulate AVX function using repeated SSE function" and the "just emulate piecewise" make some function (including min and max) generating bad code for AVX emulation of itnegers operations. 

I'm pushing a branch so you can check if it is better and I'll fix all those if this is the case.

**Comment by jfalcou** [comment]
I think you can give a shot at branch issue_519

**Comment by ThomasRetornaz** [comment]
Hi i checkout the branch issue_519 and make some test on
- infimum bs:min
- supremum bs:max
- satured add bs::saturated_(bs::plus)
- saturated sub bs::saturated_(bs::minus)

For 1000*1000 vector of unsigned char aligned and 10000 iteration using **avx** intruction set (time in ms)

|                                        | Scalar  |                                   Simd|
|infimum                           |    847  |                                       928|
|supremum                       |    839  |                                       923|
|saturatedadd                   | 11301 |                                   19248|
|saturatedsub                   |   8810 |                                    25000|



For 1000*1000 vector of unsigned char aligned and 10000 iteration using **SSE2** intruction set (time in ms)


|                                        | Scalar|                                     Simd|
|infimum                           |    850|                                         847|
|supremum                       |    846|                                         833| 
|saturatedadd                   | 10901|                                        806|
|saturatedsub                   |   8506|                                        807|


I hope i don't make a mistake
Its seems that a "similar" problem exist for saturated add and sub using **AVX** instruction set
And  i have to buy a Haswell  CPU ;)
Regards
TR

**Comment by jfalcou** [comment]
OK, I suspect the simialr timing with scalar is due to MSVC autovectorizing. 
As for the saturated thing, yes, it's a similar issue but casued by somethign else. Fix incoming.

We will although go through the release this week as planned and add the fix for those afterward.

**Comment by ThomasRetornaz** [comment]
Obviously yes for autovectorizing, 
Stay me tuned for fix i will check on my desk
I switch to develop branch or i rest on issue_519 ?
Have a good day
Regards 
TR

**Comment by jfalcou** [comment]
You can test issue_519 again as I updated it.

**Comment by jfalcou** [comment]
You may want to reset --hard the branch though as we forced push it

**Comment by ThomasRetornaz** [comment]
For 1000*1000 vector of unsigned char aligned and 10000 iteration using **AVX** intruction set (time in ms)

| | Scalar | Simd|
|saturatedadd | 11301 | 894 |
|saturatedsub | 10941 | 901 |

For 1000*1000 vector of unsigned char aligned and 10000 iteration using **SSE2** intruction set (time in ms)
| | Scalar | Simd|
|saturatedadd | 11480 | 848 |
|saturatedsub | 9091 | 851 |

Work as expected with substantial speedup :)

Do you think over operator could share similar problems?
I could check on my desk
Regards
TR

**Comment by jfalcou** [comment]
Maybe I need to launch a massive becnhmarks suite on MSVC and see. Meanwhile, I'm turning this into a long standing issue in the MSVC Performances subproject.

**Comment by ThomasRetornaz** [comment]
If i may help
OK i think those fixes will be back-ported on develop branch right ? (after release of course) so i will switch on it 
Regards

**Comment by jfalcou** [comment]
Yes, I'm merging them asap.
