### ISSUE TITLE
pack<logical<T>> support

### ISSUE THREAD

**Issue by jfalcou** [agenium-scale/boost.simd#53]
requires a bunch of specialisation around pack_traits and storage_type

**Comment by jfalcou** [comment]
@jtlap @ccharly  I'm pondering if now that we work with pack<T,N> only, isn't 

```
pack<bool,N>
```

viable as we don't have any source of confusion and we can choose to use w/e type inside the pack of bool.

**Comment by jtlap** [comment]
Up to you

**Comment by mgaunard** [comment]
it's still better to use the correct type as on some x86 microarchitectures you'll get a penalty if using andps with registers previously executing instructions on the integer unit (and vice versa).
Nevertheless `pack<bool, N>` could be supported on top of logical for the people that do not care.

**Comment by jfalcou** [comment]
I fear it may confuse ppl to have both. The other issue I see afterward is stuff like genmask which return type will then be complicated to fetch.

**Comment by jfalcou** [comment]
logical now works with pack. We need to fill up its function.

I'll experiment with pack<bool,N> later.
