### ISSUE TITLE
Implicit cast

### ISSUE THREAD

**Issue by johnmcfarlane** [agenium-scale/boost.simd#534]
In issue #17, the choice was made not to support `static_cast<pack<T>>(pack<U>)`. This prevents `pack` from being used in generic code. It is not inter-operable with fundamental scalar types which is an obstacle to using types such as `sg14::fixed_point<pack<T>>`.

Adding the following member definition to `pack` fixes [this CI failure](https://travis-ci.org/johnmcfarlane/fixed_point/jobs/249692473) in [this branch](https://github.com/johnmcfarlane/fixed_point/pull/265) in fixed_point:

```c++
    /// @brief Converesion to another pack
    template<typename U>
    explicit BOOST_FORCEINLINE operator rebind<U>() BOOST_NOEXCEPT
    {
      typename rebind<U>::storage_type lhs_data;
      std::copy(std::begin(data_), std::end(data_), std::begin(lhs_data));
      return lhs_data;
    }
```

Note the `explicit` keyword which minimizes the situations where this operator would be considered. Also notice how happy `std::copy` is converting between scalar types. Ideally, `pack` should be just as flexible. I understand the desire to make it harder to use SIMD in suboptimal ways but unfortunately, that is a concern which gets in the way of interoperability. A better solution IMHO would be to make Boost.SIMD work with libraries such as [type_safe](https://github.com/foonathan/type_safe).

LMK what you think. I'm sure you can write a better implementation of the above function(!) but by all means recommend a PR that I can make against boost.simd if that makes things easier.

**Comment by jfalcou** [comment]
The casting function between pack is `pack<T,N> pack_cast<T>(pack<U,N> const&)`.

I'm not a big fan of implicit costly operations but I would like to see if using pack_cast in an explicit flagged operator U() 
  1/ indeed solves your issue of genericity 
  2/ don't make silent error popping up.

Let's say a PR with this feature can be a nice experiment to see if it make sense to enable it this way.

**Comment by jfalcou** [comment]
PR #538 fixes that. Thanks
