### ISSUE TITLE
What is going on?

### ISSUE THREAD

**Issue by hannespetur** [agenium-scale/boost.simd#544]
I came here to update my local Boost.SIMD to the latest version, only to see that the entire git history has been erased. Can anyone tell me what is happening?

**Comment by JPenuchot** [comment]
FMA3 & AVX/AVX2 have been removed from the master branch, they must have removed the commits that included support for these architectures.

**Comment by jfalcou** [comment]
We're currently reshaping the scope of the open version. The repo will got through various changes till then. Sorry for the inconvenience.
