### ISSUE TITLE
pack<T,N> alignment

### ISSUE THREAD

**Issue by jtlap** [agenium-scale/boost.simd#57]
It is legitimate to align pack<T> on the sizeof(pack < T > ::storage_type) to be able to perform
aligned loads when pack<T> corresponds to a native simd vector.

 But this is not correct for all pack<T,N>
alignement on  sizeof(pack < T,N   > ::storage_type) is not needed if N is greater than pack < T > ::static_size

Perhaps for all Ns sizeof(pack < T > ::storage_type) can do the job.

I don't really know where to enforce that or it's only to be a documentation part ?

**Comment by jtlap** [comment]
Yes of course at least the assert in the aligned_load calls must be modified ;  
BOOST_ASSERT_MSG( boost::alignment::is_aligned(p, sizeof(target))...

**Comment by jfalcou** [comment]
We can just overload boost::align::alignment_of and use that.

**Comment by mgaunard** [comment]
the current std proposal has a constexpr value inside the class that says what the required alignment is

**Comment by jfalcou** [comment]
I think this should be the job of aligned_as and cohot, which boost::align try to emulate. I'll put the constexpr and fwd it through the align overload
