### ISSUE TITLE
Provide sse3-style operations

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#6]
`addsub`, `hadd` and `hsub`.

**Comment by jfalcou** [comment]
Idea: wrap addsub into  : 

```
x = interleaved_(add,sub)(x,y);
```

generalized to any pair of binary elementwise functions and optimizes the one that make sense ?
interleave_first/second are basically interleaved_(assign,assign).

**Comment by jfalcou** [comment]
There is no proper abstraction that fit  those. We'll use them when needed but direct access is for now not provided

**Comment by jfalcou** [comment]
After some thinking, @gquintin  and @sjubertie found a way to make it properly done everywhere. the addsub branch provides this implementation.
