### ISSUE TITLE
Convenient boost.simd.memory specializations

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#7]
Add helper to allocate memory that is automatically aligned with cache alignment.

[original issue here](https://github.com/jfalcou/nt2/issues/514).

**Comment by jfalcou** [comment]
The more I think of it, the more I think it's the job of Boost.Alignment. I'm tempted to close this one. Any opinions ?

**Comment by jfalcou** [comment]
A `boost::simd::allocator<Type,Cardinal>` has been added so the computation of the requried alignment is more or less transparent.

For now, I'll consider it enough. If more specific needs arise that Boost.Align can't honor, we'll consider adding them
